visibleToClient:
    frontend:
        IP: proda.postech.ac.kr
        Port: 40080
        Protocol: https # Either https or http
    backend:
        IP: proda.postech.ac.kr
        Port: 40102
        Protocol: https # Either https or http
backend:
    IP: localhost
    Port: 4002
    Protocol: https # Either https or http
DB:
    IP: localhost
    Port: 5432
    config:
        DBName: proda_config
        UserID: config_user
        UserPW: config_user_pw
        TableName: config
        QueryGoalNumsTableName: query_goal
    demo:
        DBName: proda_demo
        UserID: demo_user
        UserPW: demo_user_pw
    collection:
        DBName: proda_collection
        UserID: collection_user
        UserPW: collection_user_pw
        CollectionTableName: collection
        TaskTableName: task
        TaskSetTableName: task_set
SSLCertPath: "/home/hjkim/PRODA/certificates/localhost.crt"
SSLKeyPath: "/home/hjkim/PRODA/certificates/localhost.key"
taskSaveDirPath: "/home/hjkim/PRODA/database/dataCollection/tasks/"
