visibleToClient:
    frontend:
        IP: proda.postech.ac.kr # Visible IP addr
        Port: 3000 # Actual port within this server
        Protocol: http # Either https or http
    backend:
        IP: proda.postech.ac.kr # Visible IP addr
        Port: 4001 # Visible port
        Protocol: http # Either https or http
    isAMTCollectionMode: false
backend:
    IP: localhost
    Port: 4001
    Protocol: http # Either https or http
DB:
    IP: localhost
    Port: 5434
    config:
        DBName: proda_config
        UserID: config_user
        UserPW: config_user_pw
        TableName: config
        QueryGoalNumsTableName: query_goal
    demo:
        DBName: proda_demo
        UserID: demo_user
        UserPW: demo_user_pw
    collection:
        DBName: proda_collection
        UserID: collection_user
        UserPW: collection_user_pw
        CollectionTableName: collection
        TaskTableName: task
        TaskSetTableName: task_set
    data:
        UserID: data_user
        UserPW: data_user_pw
ProjectPath: "/root/proda"
SSLCertPath: "./certificates/localhost.crt"
SSLKeyPath: "./certificates/localhost.key"
SSLCaPath: "./certificates/DigiCertCA.pem"
TaskSaveDirPath: "database/dataCollection/tasks/"
DBPath: "/home/hjkim/DATA/"
