version: "3"

services:
    proda:
        image: hyukkyukang/proda:latest
        container_name: proda
        # stdin_open: true
        tty: true
        network_mode: "host"
        ports:
            - "3000:3000"
            - "4001:4001"
        volumes:
            - ./:/root/proda/
    proda-postgres:
        image: postgres:15.1
        container_name: proda-postgres
        stdin_open: true
        tty: true
        ports:
            - "5434:5432"
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
        volumes:
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - ./data/postgresql:/var/lib/postgresql/data
