version: '3'

services:
    proda:
        image: hyukkyukang/proda:latest
        # stdin_open: true
        tty: true
        network_mode: "host"
        ports:
            - "3000:3000"
            - "4000:4000"
            - "5432:5432"
        volumes:
            - .:/home/proda