SELECT O_Student.city_code, O_Student.Sex FROM Student O_Student WHERE (O_Student.Major < (SELECT AVG(I_Student.Major) FROM Student I_Student WHERE I_Student.Fname LIKE "Mark%") OR (O_Student.Fname NOT LIKE "%Mark%" OR O_Student.LName IN "('Davis','Andreou')"))
SELECT O_Student.Age, O_Student.Advisor FROM Student O_Student WHERE (SELECT Student.city_code, MIN(I_Student.Major) FROM Student I_Student WHERE (O_Student.Sex = I_Student.Sex AND (I_Student.Fname != "Derek" AND I_Student.Fname IN "('Eric','Mark','Linda','Paul')")) GROUP BY Student.city_code ORDER BY Student.Fname LIMIT 4) >= 50
SELECT Student.Age, AVG(O_Student.StuID) FROM Student O_Student WHERE O_Student.Age <= (SELECT Student.Age, SUM(I_Student.Age) FROM Student I_Student WHERE (O_Student.LName = I_Student.LName AND I_Student.LName LIKE "%Kim") GROUP BY Student.Age) GROUP BY Student.Age
SELECT * FROM Student O_Student WHERE ((SELECT I_Student.Age FROM Student I_Student WHERE (O_Student.Major = I_Student.Major AND ((I_Student.Fname LIKE "%Mark%" AND I_Student.LName != "Kim") OR I_Student.Fname LIKE "%Mark%"))) <= 17 OR O_Student.Fname NOT LIKE "Stacy%")
SELECT COUNT(DISTINCT O_Student.city_code) FROM Student O_Student WHERE (O_Student.Major != 50 OR O_Student.Advisor < (SELECT AVG(I_Student.Advisor) FROM Student I_Student))
SELECT Student.Age, SUM(O_Student.StuID) FROM Student O_Student WHERE O_Student.Age != (SELECT Student.Age, MAX(I_Student.Age) FROM Student I_Student WHERE (I_Student.Fname IN "('Arthur','Bruce')" OR I_Student.Sex = "M") GROUP BY Student.Age HAVING COUNT(Student.Major) != 4) GROUP BY Student.Age HAVING (COUNT(Student.city_code) >= 3 AND (COUNT(Student.LName) > 3 AND COUNT(Student.Sex) != 3))
SELECT COUNT(DISTINCT O_Student.LName), COUNT(DISTINCT O_Student.city_code) FROM Student O_Student WHERE O_Student.city_code IN (SELECT I_Student.city_code FROM Student I_Student WHERE (O_Student.Fname = I_Student.Fname AND I_Student.LName IN "('Goldman','Andreou','Pang','Brody')") ORDER BY Student.Sex LIMIT 3) ORDER BY Student.Fname
SELECT Student.Major, MAX(O_Student.Major) FROM Student O_Student WHERE (SELECT Student.Age, SUM(I_Student.Major) FROM Student I_Student WHERE (O_Student.LName = I_Student.LName AND ((I_Student.Sex NOT LIKE "%F%" OR I_Student.city_code LIKE "PIT%") OR I_Student.Age > 17)) GROUP BY Student.Age ORDER BY MIN(Student.Major) LIMIT 1) < 30760 GROUP BY Student.Major HAVING (Student.Major >= 50 OR SUM(Student.Age) < 18) ORDER BY MAX(Student.Advisor) LIMIT 2
SELECT Student.Age, COUNT(*) FROM Student O_Student WHERE (O_Student.LName IN "('Woods','Leighton','Brown')" AND O_Student.Advisor >= (SELECT MIN(I_Student.Advisor) FROM Student I_Student WHERE (I_Student.Sex LIKE "%M%" OR I_Student.city_code IN "('LOS','DET')"))) GROUP BY Student.Age HAVING (COUNT(Student.LName) >= 4 AND (SUM(Student.Major) != 550 AND COUNT(Student.city_code) <= 3))
SELECT Student.Age, COUNT(*) FROM Student O_Student WHERE O_Student.LName NOT IN (SELECT Student.Sex, I_Student.LName FROM Student I_Student GROUP BY Student.Sex ORDER BY Student.Sex LIMIT 1) GROUP BY Student.Age
SELECT AVG(O_Student.Advisor), SUM(O_Student.Age) FROM Student O_Student WHERE (O_Student.Sex NOT LIKE "%F%" AND (O_Student.Fname NOT IN "('Stacy','Derek')" AND O_Student.city_code LIKE (SELECT I_Student.city_code FROM Student I_Student WHERE ((I_Student.Advisor = 7712 AND I_Student.LName LIKE "%Kim%") OR I_Student.city_code NOT LIKE "%NAR%")))) ORDER BY Student.Fname LIMIT 4
SELECT Student.Advisor, COUNT(*) FROM Student O_Student WHERE (O_Student.Fname NOT IN (SELECT Student.Major, I_Student.Fname FROM Student I_Student GROUP BY Student.Major) AND (O_Student.Sex NOT LIKE "%M" OR O_Student.Major != 600)) GROUP BY Student.Advisor HAVING (COUNT(Student.Fname) = 4 AND COUNT(Student.Fname) = 3) ORDER BY Student.Sex LIMIT 2
SELECT Student.Age, AVG(O_Student.Age) FROM Student O_Student WHERE O_Student.Advisor >= (SELECT AVG(I_Student.Advisor) FROM Student I_Student WHERE (I_Student.Sex IN "('F','M')" AND I_Student.Advisor != 2311) ORDER BY Student.LName) GROUP BY Student.Age HAVING Student.Age = 18
SELECT Student.Age, COUNT(*) FROM Student O_Student WHERE (O_Student.Advisor <= 8722 OR (O_Student.Advisor = (SELECT Student.Advisor, MAX(I_Student.Advisor) FROM Student I_Student WHERE (I_Student.city_code != "PEK" AND I_Student.Advisor = 8423) GROUP BY Student.Advisor) AND O_Student.city_code LIKE "PIT%")) GROUP BY Student.Age ORDER BY MIN(Student.Advisor)
SELECT Student.Sex, COUNT(DISTINCT O_Student.Major), MAX(O_Student.StuID) FROM Student O_Student WHERE ((O_Student.Major > 520 OR (SELECT Student.city_code, COUNT(I_Student.Major) FROM Student I_Student WHERE (O_Student.Age = I_Student.Age AND (I_Student.Advisor >= 2192 AND (I_Student.Sex NOT LIKE "F%" OR I_Student.Fname != "George"))) GROUP BY Student.city_code HAVING (COUNT(Student.LName) >= 2 AND COUNT(Student.Major) = 2) ORDER BY Student.Sex LIMIT 3) != 33) OR O_Student.LName IN "('Rugh','Epp','Kumar','Cheng','Smith')") GROUP BY Student.Sex
SELECT O_Student.StuID, O_Student.Advisor FROM Student O_Student WHERE (O_Student.Fname = "David" AND ((SELECT Student.Fname, COUNT(I_Student.Fname) FROM Student I_Student WHERE (O_Student.LName = I_Student.LName AND (I_Student.city_code NOT LIKE "%YYZ%" OR I_Student.Age < 19)) GROUP BY Student.Fname) != 25 AND O_Student.Major < 550))
SELECT Student.LName, SUM(O_Has_Pet.StuID) FROM Has_Pet O_Has_Pet JOIN Student O_Student ON O_Student.StuID=O_Has_Pet.StuID WHERE (O_Student.Age != 18 OR (SELECT Student.city_code, COUNT(I_Student.Fname) FROM Student I_Student WHERE (O_Student.city_code = I_Student.city_code AND I_Student.Age < 21) GROUP BY Student.city_code HAVING (COUNT(Student.Fname) = 2 OR MAX(Student.Advisor) = 8772)) >= 73) GROUP BY Student.LName HAVING COUNT(Student.Advisor) <= 4
SELECT O_Student.Advisor FROM Student O_Student WHERE (O_Student.Fname NOT IN (SELECT Student.Fname, I_Student.Fname FROM Student I_Student GROUP BY Student.Fname ORDER BY Student.city_code) OR (O_Student.LName NOT LIKE "Prater%" AND O_Student.Sex != "F"))
SELECT * FROM Student O_Student WHERE (((SELECT Student.LName, MAX(I_Student.Major) FROM Student I_Student WHERE (O_Student.Sex = I_Student.Sex AND (I_Student.Sex != "'M'" OR I_Student.Major = 600)) GROUP BY Student.LName HAVING (Student.LName = "Nelson" OR COUNT(Student.city_code) != 4)) <= 600 AND O_Student.Sex != "F") OR O_Student.Age = 20)
SELECT O_Student.city_code FROM Student O_Student WHERE ((O_Student.city_code LIKE (SELECT Student.Advisor, I_Student.city_code FROM Student I_Student GROUP BY Student.Advisor HAVING MIN(Student.Major) = 550) AND O_Student.Age > 17) AND O_Student.Sex != "'F'") ORDER BY Student.Major LIMIT 2
SELECT Student.Sex, COUNT(*) FROM Student O_Student WHERE (O_Student.Advisor <= (SELECT SUM(I_Student.Advisor) FROM Student I_Student WHERE I_Student.Major = 520) OR O_Student.city_code != "PHL") GROUP BY Student.Sex HAVING AVG(Student.Age) > 17
SELECT Student.Major, COUNT(*) FROM Student O_Student WHERE (O_Student.city_code = "LON" OR (O_Student.Age != 18 AND O_Student.city_code NOT IN (SELECT I_Student.city_code FROM Student I_Student WHERE (I_Student.city_code = "CHI" OR I_Student.Major != 600)))) GROUP BY Student.Major ORDER BY COUNT(Student.city_code) LIMIT 4
SELECT * FROM Student O_Student WHERE O_Student.city_code IN (SELECT Student.Age, I_Student.city_code FROM Student I_Student GROUP BY Student.Age ORDER BY Student.Fname LIMIT 3)
SELECT Student.Fname, AVG(O_Student.StuID), COUNT(DISTINCT O_Student.LName) FROM Student O_Student WHERE (((SELECT AVG(I_Student.Age) FROM Student I_Student WHERE (O_Student.Sex = I_Student.Sex AND I_Student.Sex != "F") ORDER BY Student.Advisor LIMIT 3) <= 19.48316251830161 OR O_Student.city_code LIKE "%DET%") OR O_Student.Major <= 520) GROUP BY Student.Fname
SELECT Student.Major, COUNT(*) FROM Student O_Student WHERE O_Student.city_code NOT IN (SELECT Student.Age, I_Student.city_code FROM Student I_Student GROUP BY Student.Age HAVING ((Student.Age > 19.0 AND MIN(Pets.weight) <= 9.3) AND Student.Age != 19.0)) GROUP BY Student.Major HAVING ((COUNT(Student.city_code) != 2 OR COUNT(Student.Fname) > 2) AND AVG(Student.Age) >= 20) ORDER BY Student.Advisor LIMIT 3
SELECT O_Student.LName, O_Student.Fname FROM Student O_Student WHERE (O_Student.Age >= 19 OR (O_Student.Age <= (SELECT SUM(I_Student.Age) FROM Student I_Student WHERE (O_Student.Sex = I_Student.Sex AND (I_Student.Advisor <= 2192 OR I_Student.Advisor = 1148)) ORDER BY Student.LName LIMIT 1) AND O_Student.Advisor != 8423))
SELECT Student.Age, SUM(O_Student.StuID) FROM Student O_Student WHERE (O_Student.Age > (SELECT Student.Age, MIN(I_Student.Age) FROM Student I_Student WHERE (O_Student.city_code = I_Student.city_code AND (I_Student.Fname NOT IN "('Derek','Stacy','Linda','Eric')" OR (I_Student.Advisor != 8918 OR I_Student.Major <= 600))) GROUP BY Student.Age HAVING (Student.Age != 18 AND (Student.Age != 18 AND Student.Age != 18))) AND (O_Student.Fname LIKE "Sarah%" OR O_Student.Age != 20)) GROUP BY Student.Age ORDER BY Student.Major LIMIT 3
SELECT Student.city_code, COUNT(DISTINCT O_Student.Sex), MAX(O_Student.Advisor) FROM Student O_Student WHERE O_Student.Age <= (SELECT Student.LName, SUM(I_Student.Age) FROM Student I_Student GROUP BY Student.LName HAVING ((MIN(Student.Advisor) != 8721 AND COUNT(Student.city_code) <= 2) AND COUNT(Student.Major) > 4) ORDER BY COUNT(Student.Sex)) GROUP BY Student.city_code HAVING (COUNT(Student.Fname) != 4 AND COUNT(Student.Sex) = 2) ORDER BY Student.Sex LIMIT 2
SELECT Student.Age, SUM(O_Student.Major), MIN(O_Student.Advisor) FROM Student O_Student WHERE (O_Student.Fname = "Mark" OR O_Student.Advisor > (SELECT Student.Major, MIN(I_Student.Advisor) FROM Student I_Student WHERE I_Student.Sex != "'F'" GROUP BY Student.Major HAVING (COUNT(Student.Sex) > 4 AND (COUNT(Student.Age) != 4 AND AVG(Student.Advisor) >= 5718)))) GROUP BY Student.Age HAVING (Student.Age = 22 OR (COUNT(Student.city_code) < 1 AND COUNT(Student.city_code) <= 4))
SELECT Student.city_code, COUNT(DISTINCT O_Student.LName) FROM Student O_Student WHERE (O_Student.Advisor = 7712 AND O_Student.Advisor <= (SELECT SUM(I_Student.Advisor) FROM Student I_Student WHERE I_Student.LName NOT LIKE "%Pang%")) GROUP BY Student.city_code HAVING (AVG(Student.Age) >= 20 AND COUNT(Student.Fname) > 4) ORDER BY Student.Fname
SELECT * FROM Student O_Student WHERE O_Student.city_code NOT IN (SELECT I_Student.city_code FROM Student I_Student WHERE (I_Student.city_code NOT LIKE "%DET%" AND I_Student.Advisor < 7271)) ORDER BY Student.Sex LIMIT 4
SELECT Student.Major, SUM(O_Student.StuID), COUNT(DISTINCT O_Student.Fname) FROM Student O_Student WHERE (O_Student.Age < 18 OR (O_Student.Advisor < 8721 AND O_Student.Major >= (SELECT I_Student.Major FROM Student I_Student WHERE (O_Student.Advisor = I_Student.Advisor AND (I_Student.Sex LIKE "%M%" AND I_Student.Fname != "Arthur"))))) GROUP BY Student.Major HAVING (Student.Major <= 100 OR COUNT(Student.Fname) != 4)
SELECT O_Student.Sex FROM Student O_Student WHERE (O_Student.Age > (SELECT AVG(I_Student.Age) FROM Student I_Student WHERE (O_Student.Advisor = I_Student.Advisor AND I_Student.city_code != "LOS")) OR O_Student.Advisor = 2192)
SELECT O_Student.Major, O_Student.Fname FROM Student O_Student WHERE (O_Student.city_code != "BAL" AND (O_Student.Advisor <= (SELECT Student.city_code, SUM(I_Student.Advisor) FROM Student I_Student GROUP BY Student.city_code) OR O_Student.Fname = "Michael")) ORDER BY Student.Major
SELECT Student.Sex, COUNT(*) FROM Student O_Student WHERE O_Student.Age <= (SELECT SUM(I_Student.Age) FROM Student I_Student) GROUP BY Student.Sex ORDER BY Student.Major
SELECT O_Student.Sex, O_Student.StuID FROM Student O_Student WHERE ((O_Student.city_code LIKE "%PEK%" OR O_Student.Major != 550) OR (SELECT Student.Age, COUNT(I_Student.city_code) FROM Student I_Student WHERE (O_Student.Advisor = I_Student.Advisor AND (I_Student.Fname NOT IN "('Bruce','George')" AND (I_Student.Fname LIKE "%Michael%" OR I_Student.city_code IN "('HOU','DAL','PHL','ROC','DET')"))) GROUP BY Student.Age) > 21) ORDER BY Student.city_code
SELECT Student.Advisor, COUNT(DISTINCT O_Student.Sex), COUNT(DISTINCT O_Student.Fname) FROM Student O_Student WHERE O_Student.Age <= (SELECT MAX(I_Student.Age) FROM Student I_Student WHERE (O_Student.Advisor = I_Student.Advisor AND I_Student.Advisor > 8772) ORDER BY Student.city_code) GROUP BY Student.Advisor
SELECT O_Student.StuID FROM Student O_Student WHERE ((O_Student.Advisor != 8722 OR O_Student.LName != (SELECT Student.Major, I_Student.LName FROM Student I_Student WHERE (O_Student.Major = I_Student.Major AND ((I_Student.Age >= 16 AND I_Student.city_code != "NYC") AND I_Student.LName NOT LIKE "%Epp%")) GROUP BY Student.Major HAVING COUNT(Student.LName) < 2)) AND O_Student.Major <= 600) ORDER BY Student.Fname LIMIT 4
SELECT Student.Advisor, COUNT(DISTINCT O_Student.Age), AVG(O_Student.StuID) FROM Student O_Student WHERE O_Student.Age <= (SELECT Student.Age, AVG(I_Student.Age) FROM Student I_Student GROUP BY Student.Age ORDER BY Student.Advisor LIMIT 4) GROUP BY Student.Advisor ORDER BY Student.Advisor LIMIT 3
SELECT Student.Major, COUNT(*) FROM Student O_Student WHERE ((O_Student.Major NOT IN (SELECT I_Student.Major FROM Student I_Student WHERE (O_Student.Sex = I_Student.Sex AND (I_Student.LName NOT LIKE "%Rugh%" AND I_Student.Age > 17)) ORDER BY Student.Fname LIMIT 4) OR O_Student.city_code NOT LIKE "%BOS%") AND O_Student.Sex LIKE "%M") GROUP BY Student.Major
SELECT Student.Sex, COUNT(*) FROM Student O_Student WHERE ((O_Student.Sex != "M" AND O_Student.Major IN (SELECT Student.city_code, I_Student.Major FROM Student I_Student GROUP BY Student.city_code HAVING (MIN(Student.Major) <= 600 AND AVG(Student.Major) >= 600))) AND O_Student.Major < 100) GROUP BY Student.Sex HAVING COUNT(Student.LName) > 3 ORDER BY Student.Sex
SELECT * FROM Student O_Student WHERE (O_Student.Major < (SELECT Student.Age, SUM(I_Student.Major) FROM Has_Pet I_Has_Pet JOIN Pets I_Pets JOIN Student I_Student ON I_Pets.PetID=I_Has_Pet.PetID AND I_Student.StuID=I_Has_Pet.StuID WHERE (O_Pets.weight = I_Pets.weight AND I_Pets.pet_age > 1.0) GROUP BY Student.Age ORDER BY MIN(Pets.pet_age) LIMIT 4) AND (O_Student.LName != "Jones" OR O_Student.Major < 600))
SELECT Student.LName, COUNT(DISTINCT O_Student.Age) FROM Student O_Student WHERE (O_Student.city_code != (SELECT Student.Sex, I_Student.city_code FROM Student I_Student GROUP BY Student.Sex HAVING MIN(Pets.pet_age) < 3.0 ORDER BY Student.Advisor) AND O_Student.Age < 22) GROUP BY Student.LName HAVING (COUNT(Student.Sex) >= 2 AND Student.LName != "Cheng")
SELECT Student.LName, COUNT(*) FROM Student O_Student WHERE ((O_Student.Advisor != 1148 AND O_Student.Major != 520) OR O_Student.Age = (SELECT Student.LName, AVG(I_Student.Age) FROM Student I_Student WHERE I_Student.Major >= 600 GROUP BY Student.LName HAVING ((COUNT(Student.city_code) != 2 AND COUNT(Student.city_code) < 1) OR SUM(Student.Major) != 600) ORDER BY Student.LName)) GROUP BY Student.LName
SELECT Student.city_code, COUNT(DISTINCT O_Student.city_code) FROM Student O_Student WHERE O_Student.Advisor IN (SELECT I_Student.Advisor FROM Student I_Student WHERE (O_Student.LName = I_Student.LName AND I_Student.Fname NOT IN "('Andy','Jun','Steven','David','Stacy')") ORDER BY Student.Advisor) GROUP BY Student.city_code
SELECT Pets.pet_age, COUNT(*) FROM Has_Pet O_Has_Pet JOIN Pets O_Pets JOIN Student O_Student ON O_Pets.PetID=O_Has_Pet.PetID AND O_Student.StuID=O_Has_Pet.StuID WHERE (O_Pets.weight >= (SELECT I_Pets.weight FROM Has_Pet I_Has_Pet JOIN Pets I_Pets JOIN Student I_Student ON I_Pets.PetID=I_Has_Pet.PetID AND I_Student.StuID=I_Has_Pet.StuID WHERE (O_Student.Major = I_Student.Major AND I_Student.LName IN "('Smith','Kumar','Brown')")) OR O_Student.Major < 600) GROUP BY Pets.pet_age ORDER BY Student.city_code LIMIT 4
SELECT Student.city_code, COUNT(*) FROM Student O_Student WHERE (O_Student.Sex NOT LIKE "%F" OR (O_Student.Age = (SELECT AVG(I_Student.Age) FROM Student I_Student) AND O_Student.Sex NOT LIKE "%F")) GROUP BY Student.city_code ORDER BY Student.LName
SELECT Student.city_code, COUNT(DISTINCT O_Student.city_code), MAX(O_Student.Major) FROM Student O_Student WHERE (O_Student.Advisor > 1121 OR O_Student.Advisor > (SELECT MIN(I_Student.Advisor) FROM Student I_Student WHERE (I_Student.Age <= 20 AND (I_Student.LName NOT LIKE "%Smith" OR I_Student.LName NOT IN "('Norris','Lee','Andreou','Cheng')")) ORDER BY Student.LName LIMIT 4)) GROUP BY Student.city_code HAVING ((COUNT(Student.Fname) >= 2 AND COUNT(Student.Sex) >= 1) OR SUM(Student.Major) <= 600)
SELECT O_Student.Advisor, O_Student.Fname FROM Student O_Student WHERE O_Student.Advisor != (SELECT MAX(I_Student.Advisor) FROM Student I_Student ORDER BY Student.city_code LIMIT 3) ORDER BY Student.Sex
SELECT * FROM Student O_Student WHERE (O_Student.Sex NOT LIKE "M%" AND (O_Student.Fname NOT IN "('Linda','George','Mark','Sarah','Paul')" OR O_Student.Fname LIKE (SELECT Student.Major, I_Student.Fname FROM Student I_Student WHERE (I_Student.city_code NOT LIKE "PHL%" OR I_Student.Major <= 550) GROUP BY Student.Major ORDER BY COUNT(Student.Fname) LIMIT 1)))
SELECT * FROM Student O_Student WHERE (O_Student.LName != (SELECT Student.LName, I_Student.LName FROM Student I_Student GROUP BY Student.LName) AND O_Student.city_code = "WAS") ORDER BY Student.Age
SELECT * FROM Student O_Student WHERE (O_Student.Fname NOT IN (SELECT Student.LName, I_Student.Fname FROM Student I_Student WHERE (I_Student.Sex != "'F'" OR I_Student.Advisor <= 1148) GROUP BY Student.LName ORDER BY Student.Age LIMIT 2) OR O_Student.city_code NOT IN "('NYC','ATL','ROC')")
SELECT Student.Advisor, COUNT(DISTINCT O_Student.Sex), AVG(O_Student.StuID) FROM Student O_Student WHERE ((O_Student.Age = 17 AND O_Student.Age <= (SELECT Student.LName, SUM(I_Student.Age) FROM Student I_Student WHERE (O_Student.Major = I_Student.Major AND (I_Student.LName != "Goldman" OR (I_Student.Major != 520 AND I_Student.city_code NOT LIKE "%ATL"))) GROUP BY Student.LName HAVING (COUNT(Student.Sex) < 1 AND MAX(Student.Age) != 20))) AND O_Student.city_code LIKE "%PHL") GROUP BY Student.Advisor ORDER BY Student.Major LIMIT 1
SELECT O_Student.Major FROM Student O_Student WHERE (SELECT I_Student.Fname FROM Student I_Student WHERE (O_Student.LName = I_Student.LName AND (I_Student.Advisor >= 1148 OR I_Student.Sex != "M"))) LIKE "Andy"
SELECT Student.Advisor, COUNT(DISTINCT O_Student.Fname), COUNT(DISTINCT O_Student.LName) FROM Student O_Student WHERE O_Student.Age < (SELECT Student.Age, AVG(I_Student.Age) FROM Student I_Student GROUP BY Student.Age ORDER BY Student.Major) GROUP BY Student.Advisor
SELECT Student.LName, COUNT(DISTINCT O_Student.city_code), MAX(O_Student.Age) FROM Student O_Student WHERE (O_Student.Sex != "'M'" OR O_Student.Fname = (SELECT I_Student.Fname FROM Student I_Student WHERE I_Student.LName LIKE "Cheng%")) GROUP BY Student.LName
SELECT Student.LName, COUNT(*) FROM Student O_Student WHERE O_Student.Age > (SELECT Student.Age, MIN(I_Student.Age) FROM Student I_Student WHERE (O_Student.city_code = I_Student.city_code AND (I_Student.city_code NOT IN "('LOS','YYZ')" AND I_Student.city_code NOT LIKE "%SFO")) GROUP BY Student.Age ORDER BY Student.Fname LIMIT 2) GROUP BY Student.LName ORDER BY Student.Fname
SELECT Student.Age, COUNT(DISTINCT O_Student.city_code) FROM Student O_Student WHERE ((O_Student.Advisor = 8772 OR (SELECT Student.LName, COUNT(I_Student.city_code) FROM Student I_Student WHERE (O_Student.Advisor = I_Student.Advisor AND I_Student.LName LIKE "%Smith%") GROUP BY Student.LName HAVING COUNT(Student.Fname) >= 1 ORDER BY Student.Advisor LIMIT 1) != 31) OR O_Student.LName = "Smith") GROUP BY Student.Age HAVING (MIN(Student.Advisor) <= 5718 OR COUNT(Student.Advisor) != 2)
SELECT Student.Sex, COUNT(*) FROM Student O_Student WHERE ((SELECT I_Student.Fname FROM Student I_Student WHERE (O_Student.city_code = I_Student.city_code AND I_Student.Sex != "'M'")) = "Andy" AND O_Student.Major >= 600) GROUP BY Student.Sex
SELECT Student.Age, COUNT(DISTINCT O_Student.LName), COUNT(DISTINCT O_Student.Fname) FROM Student O_Student WHERE O_Student.Age != (SELECT AVG(I_Student.Age) FROM Student I_Student ORDER BY Student.Advisor) GROUP BY Student.Age ORDER BY Student.Major LIMIT 3
SELECT * FROM Student O_Student WHERE ((SELECT Student.Sex, COUNT(I_Student.city_code) FROM Student I_Student WHERE (O_Student.Sex = I_Student.Sex AND I_Student.Fname IN "('Bruce','Lisa','Derek','Eric')") GROUP BY Student.Sex ORDER BY Student.Age) > 47 AND (O_Student.Age = 18 OR O_Student.Major > 600))
SELECT * FROM Student O_Student WHERE O_Student.Advisor = (SELECT AVG(I_Student.Advisor) FROM Student I_Student WHERE (O_Student.Age = I_Student.Age AND ((I_Student.Age >= 18 OR I_Student.Sex LIKE "M%") AND I_Student.Fname = "Steven")))
SELECT Student.LName, COUNT(*) FROM Student O_Student WHERE ((O_Student.Fname NOT IN "('Dinesh','Steven','Ian')" AND O_Student.LName NOT LIKE "%Rugh") OR O_Student.Age <= (SELECT AVG(I_Student.Age) FROM Student I_Student ORDER BY Student.Age LIMIT 3)) GROUP BY Student.LName ORDER BY AVG(Student.Advisor)
SELECT Student.Fname, COUNT(*) FROM Student O_Student WHERE O_Student.Age <= (SELECT Student.city_code, MAX(I_Student.Age) FROM Student I_Student WHERE I_Student.Sex NOT LIKE "%M" GROUP BY Student.city_code HAVING MIN(Student.Age) <= 26) GROUP BY Student.Fname
SELECT Student.Major, COUNT(*) FROM Student O_Student WHERE O_Student.Fname IN (SELECT Student.Major, I_Student.Fname FROM Student I_Student WHERE (O_Student.Advisor = I_Student.Advisor AND ((I_Student.LName LIKE "Andreou%" OR I_Student.Major < 600) OR I_Student.Sex NOT LIKE "%F")) GROUP BY Student.Major HAVING (MIN(Student.Advisor) = 2311 AND COUNT(Student.Fname) < 2)) GROUP BY Student.Major
SELECT Student.Major, COUNT(DISTINCT O_Student.LName), COUNT(DISTINCT O_Student.Fname) FROM Student O_Student WHERE O_Student.city_code LIKE (SELECT Student.Major, I_Student.city_code FROM Student I_Student GROUP BY Student.Major ORDER BY SUM(Student.Age) LIMIT 2) GROUP BY Student.Major ORDER BY COUNT(Student.LName) LIMIT 2
SELECT O_Student.StuID, O_Student.LName FROM Student O_Student WHERE (SELECT I_Student.city_code FROM Student I_Student WHERE (O_Student.Major = I_Student.Major AND I_Student.LName = "Kim")) LIKE "HKG" ORDER BY Student.Advisor LIMIT 4
SELECT O_Student.Advisor FROM Student O_Student WHERE ((SELECT SUM(I_Student.Age) FROM Student I_Student WHERE (O_Student.Fname = I_Student.Fname AND (I_Student.city_code NOT LIKE "%SFO" OR I_Student.LName IN "('Pang','Prater','Smith')")) ORDER BY Student.city_code LIMIT 2) != 450 OR O_Student.Advisor > 2311) ORDER BY Student.Advisor
SELECT * FROM Student O_Student WHERE O_Student.Sex LIKE (SELECT I_Student.Sex FROM Student I_Student WHERE (O_Student.Age = I_Student.Age AND ((I_Student.Fname LIKE "Lisa%" AND I_Student.Advisor >= 2311) AND I_Student.Sex != "'M'")) ORDER BY Student.Advisor LIMIT 4) ORDER BY Student.Age
SELECT O_Student.Advisor FROM Student O_Student WHERE O_Student.Advisor <= (SELECT Student.LName, MAX(I_Student.Advisor) FROM Student I_Student WHERE (I_Student.Fname != "Andy" AND I_Student.Age <= 21) GROUP BY Student.LName ORDER BY Student.LName) ORDER BY Student.LName LIMIT 3
SELECT O_Student.Major FROM Student O_Student WHERE ((O_Student.Major >= 550 OR O_Student.Major >= 600) AND O_Student.Advisor >= (SELECT AVG(I_Student.Advisor) FROM Student I_Student ORDER BY Student.Advisor LIMIT 4)) ORDER BY Student.Fname
SELECT COUNT(DISTINCT O_Student.Sex), COUNT(DISTINCT O_Student.LName) FROM Student O_Student WHERE O_Student.Major != (SELECT MIN(I_Student.Major) FROM Student I_Student WHERE (O_Student.Fname = I_Student.Fname AND (I_Student.city_code LIKE "%NYC%" OR (I_Student.Major <= 520 OR I_Student.Major = 600))))
SELECT Student.city_code, COUNT(*) FROM Student O_Student WHERE (O_Student.Advisor != (SELECT Student.LName, SUM(I_Student.Advisor) FROM Student I_Student WHERE (O_Student.Sex = I_Student.Sex AND (I_Student.Major != 520 OR I_Student.LName = "Davis")) GROUP BY Student.LName ORDER BY SUM(Student.Advisor)) OR O_Student.LName LIKE "%Andreou%") GROUP BY Student.city_code
SELECT O_Student.Sex FROM Student O_Student WHERE (O_Student.Fname IN "('Mark','William','Jun','Susan','Arthur')" OR O_Student.Advisor < (SELECT Student.Major, I_Student.Advisor FROM Student I_Student GROUP BY Student.Major ORDER BY Student.Fname)) ORDER BY Student.Fname
SELECT COUNT(DISTINCT O_Student.LName) FROM Student O_Student WHERE (SELECT Student.LName, AVG(I_Student.Age) FROM Student I_Student WHERE (O_Student.Major = I_Student.Major AND I_Student.city_code = "YYZ") GROUP BY Student.LName) >= 22.84313725490196
SELECT Student.LName, MAX(O_Student.Advisor), COUNT(DISTINCT O_Student.Age) FROM Student O_Student WHERE (O_Student.Advisor IN (SELECT I_Student.Advisor FROM Student I_Student WHERE I_Student.city_code IN "('DAL','PIT','HKG','LON')" ORDER BY Student.city_code LIMIT 2) AND O_Student.Advisor >= 8772) GROUP BY Student.LName HAVING (Student.LName != "Kumar" OR COUNT(Student.Age) < 1)
SELECT Student.LName, SUM(O_Student.StuID), MAX(O_Student.Advisor) FROM Student O_Student WHERE O_Student.Sex LIKE (SELECT Student.LName, I_Student.Sex FROM Student I_Student GROUP BY Student.LName HAVING (COUNT(Student.Fname) >= 1 AND COUNT(Student.Fname) = 3) ORDER BY Student.Major LIMIT 1) GROUP BY Student.LName ORDER BY COUNT(Student.Fname)
SELECT * FROM Student O_Student WHERE (O_Student.Advisor != (SELECT Student.Major, I_Student.Advisor FROM Student I_Student GROUP BY Student.Major) OR (O_Student.Age < 20 AND O_Student.Fname NOT IN "('Susan','Ian','Paul','Dinesh')"))
SELECT COUNT(*) FROM Student O_Student WHERE (O_Student.Sex != "M" OR O_Student.Sex NOT IN (SELECT I_Student.Sex FROM Student I_Student WHERE (I_Student.city_code LIKE "NYC%" OR I_Student.Fname = "George")))
SELECT Student.Sex, COUNT(*) FROM Student O_Student WHERE (O_Student.Fname NOT LIKE "Charles%" OR O_Student.LName != (SELECT I_Student.LName FROM Student I_Student WHERE (O_Student.Age = I_Student.Age AND (I_Student.city_code LIKE "BAL%" AND I_Student.city_code NOT LIKE "%DAL")) ORDER BY Student.Major LIMIT 2)) GROUP BY Student.Sex HAVING COUNT(Student.LName) = 1 ORDER BY Student.Sex
SELECT O_Student.StuID FROM Student O_Student WHERE (O_Student.Major <= 520 OR O_Student.Advisor > (SELECT Student.city_code, I_Student.Advisor FROM Student I_Student WHERE (O_Student.Age = I_Student.Age AND (I_Student.Age != 21 OR I_Student.city_code = "BAL")) GROUP BY Student.city_code)) ORDER BY Student.Fname LIMIT 3
SELECT O_Student.Sex FROM Student O_Student WHERE O_Student.Advisor = (SELECT MIN(I_Student.Advisor) FROM Student I_Student WHERE (O_Student.Sex = I_Student.Sex AND (I_Student.Major != 520 OR I_Student.Sex = "M")) ORDER BY Student.LName)
SELECT * FROM Student O_Student WHERE O_Student.LName IN (SELECT I_Student.LName FROM Has_Pet I_Has_Pet JOIN Pets I_Pets JOIN Student I_Student ON I_Pets.PetID=I_Has_Pet.PetID AND I_Student.StuID=I_Has_Pet.StuID WHERE (I_Student.LName NOT IN "('Goldman','Jones','Woods')" OR I_Pets.weight < 13.4)) ORDER BY Student.Fname LIMIT 1
SELECT * FROM Student O_Student WHERE ((O_Student.city_code NOT IN "('HKG','PEK','ROC','PIT','NYC')" OR O_Student.city_code != (SELECT I_Student.city_code FROM Student I_Student WHERE (I_Student.Major >= 600 AND (I_Student.Sex IN "('M','F')" OR I_Student.Sex LIKE "F%")))) OR O_Student.city_code NOT IN "('DET','PIT','WAS')") ORDER BY Student.Sex
SELECT O_Student.StuID FROM Student O_Student WHERE (O_Student.Advisor = 8918 AND O_Student.Advisor != (SELECT Student.city_code, SUM(I_Student.Advisor) FROM Student I_Student GROUP BY Student.city_code)) ORDER BY Student.LName
SELECT Student.LName, COUNT(DISTINCT O_Student.Sex) FROM Student O_Student WHERE (O_Student.city_code IN "('BAL','NAR','ROC')" OR O_Student.Major >= (SELECT SUM(I_Student.Major) FROM Student I_Student ORDER BY Student.Major LIMIT 3)) GROUP BY Student.LName HAVING AVG(Student.Age) < 18
SELECT AVG(O_Student.Age) FROM Student O_Student WHERE O_Student.Age NOT IN (SELECT I_Student.Age FROM Student I_Student ORDER BY Student.Age LIMIT 4) ORDER BY Student.Age LIMIT 3
SELECT COUNT(DISTINCT O_Student.Advisor), MIN(O_Student.Advisor) FROM Student O_Student WHERE ((O_Student.Fname NOT LIKE "%Tracy" AND O_Student.city_code IN "('BAL','CHI','YYZ','DAL')") AND O_Student.Advisor >= (SELECT Student.LName, AVG(I_Student.Advisor) FROM Student I_Student WHERE (I_Student.city_code NOT LIKE "%BAL" OR I_Student.LName IN "('Schwartz','Lee','Han','Pang','Norris')") GROUP BY Student.LName HAVING COUNT(Student.Fname) > 3)) ORDER BY Student.city_code LIMIT 1
SELECT COUNT(DISTINCT O_Student.Sex), COUNT(DISTINCT O_Student.LName) FROM Student O_Student WHERE (O_Student.Major = (SELECT I_Student.Major FROM Student I_Student WHERE (O_Student.Fname = I_Student.Fname AND I_Student.LName != "Prater") ORDER BY Student.LName LIMIT 1) OR O_Student.Sex NOT LIKE "F%") ORDER BY Student.city_code
SELECT Student.Sex, COUNT(DISTINCT O_Student.city_code), MAX(O_Student.StuID) FROM Student O_Student WHERE (O_Student.Major >= (SELECT Student.city_code, I_Student.Major FROM Student I_Student GROUP BY Student.city_code HAVING COUNT(Student.Advisor) <= 2) OR (O_Student.Sex != "F" AND O_Student.LName != "Brody")) GROUP BY Student.Sex ORDER BY SUM(Student.Age)
SELECT Student.Major, COUNT(*) FROM Student O_Student WHERE ((SELECT Student.Fname, I_Student.Fname FROM Student I_Student WHERE (O_Student.Sex = I_Student.Sex AND ((I_Student.Advisor != 8721 OR I_Student.Age <= 18) AND I_Student.Age <= 18)) GROUP BY Student.Fname HAVING MIN(Student.Major) <= 550 ORDER BY Student.Major LIMIT 3) != "Stacy" AND (O_Student.Age < 18 AND O_Student.LName IN "('Lee','Schultz','Jones')")) GROUP BY Student.Major
SELECT Student.Age, COUNT(DISTINCT O_Student.LName), COUNT(DISTINCT O_Student.Sex) FROM Student O_Student WHERE ((O_Student.Fname != "Derek" AND O_Student.Age < (SELECT I_Student.Age FROM Student I_Student WHERE (I_Student.Age >= 20 AND (I_Student.Sex != "M" AND I_Student.LName = "Smith")))) AND O_Student.Age <= 18) GROUP BY Student.Age ORDER BY COUNT(Student.Fname)
SELECT O_Student.city_code, O_Student.Sex FROM Student O_Student WHERE O_Student.Advisor <= (SELECT Student.Major, AVG(I_Student.Advisor) FROM Student I_Student WHERE I_Student.Major = 550 GROUP BY Student.Major)
SELECT * FROM Student O_Student WHERE ((O_Student.Advisor <= (SELECT SUM(I_Student.Advisor) FROM Student I_Student) AND O_Student.Sex NOT LIKE "M%") AND O_Student.Advisor > 5718)
SELECT O_Student.Major FROM Student O_Student WHERE (O_Student.Advisor = 7134 OR (O_Student.Advisor < (SELECT AVG(I_Student.Advisor) FROM Student I_Student WHERE (I_Student.Major != 600 AND I_Student.Fname NOT LIKE "%William%") ORDER BY Student.LName LIMIT 2) AND O_Student.Fname NOT LIKE "%Ian%")) ORDER BY Student.Fname LIMIT 3
SELECT Student.Advisor, COUNT(DISTINCT O_Student.LName), AVG(O_Student.StuID) FROM Student O_Student WHERE (O_Student.Advisor NOT IN (SELECT Student.Major, I_Student.Advisor FROM Student I_Student WHERE (I_Student.Age <= 19 AND I_Student.Sex != "'M'") GROUP BY Student.Major HAVING (MAX(Student.Age) = 18 AND (MIN(Student.Age) != 18 AND COUNT(Student.Sex) >= 1)) ORDER BY COUNT(Student.LName)) OR O_Student.LName IN "('Woods','Han','Lee')") GROUP BY Student.Advisor HAVING COUNT(Student.LName) <= 4 ORDER BY Student.Major LIMIT 4
SELECT Student.Sex, COUNT(DISTINCT O_Student.LName), COUNT(DISTINCT O_Student.Sex) FROM Student O_Student WHERE (O_Student.Sex = "F" OR (O_Student.Age = (SELECT Student.Sex, I_Student.Age FROM Student I_Student WHERE I_Student.Age <= 22 GROUP BY Student.Sex ORDER BY COUNT(Student.Age) LIMIT 2) OR O_Student.Fname NOT IN "('Lisa','George','Jandy')")) GROUP BY Student.Sex
SELECT Student.Sex, SUM(O_Student.Major), COUNT(DISTINCT O_Student.Major) FROM Student O_Student WHERE (O_Student.city_code != "CHI" AND (O_Student.Sex IN (SELECT Student.city_code, I_Student.Sex FROM Student I_Student GROUP BY Student.city_code) OR O_Student.Fname != "Jun")) GROUP BY Student.Sex ORDER BY Student.Sex
SELECT COUNT(*) FROM Student O_Student WHERE (O_Student.Advisor < (SELECT SUM(I_Student.Advisor) FROM Student I_Student WHERE (O_Student.Fname = I_Student.Fname AND ((I_Student.Age < 18 OR I_Student.Advisor > 2311) OR I_Student.Major != 540))) OR O_Student.Sex IN "('M','F')")
SELECT Student.Major, COUNT(*) FROM Student O_Student WHERE (O_Student.Age <= 19 AND (O_Student.Advisor < (SELECT MAX(I_Student.Advisor) FROM Student I_Student WHERE (O_Student.city_code = I_Student.city_code AND (I_Student.Sex NOT LIKE "F%" OR I_Student.Fname NOT LIKE "%Tracy%")) ORDER BY Student.Fname) AND O_Student.Major < 550)) GROUP BY Student.Major HAVING (COUNT(Student.LName) < 1 AND COUNT(Student.Sex) <= 4) ORDER BY Student.Advisor
