export const operatorDescriptions = {
    "<": "This is an operator used to compare two values and return a Boolean value of true or false depending on whether the left operand is less than the right operand. The operator can be used with a variety of data types, including integers, floating-point numbers, and strings.",
    ">": "'Greater than' is an operator used to compare two values and return a Boolean value of true or false depending on whether the left operand is greater than the right operand. The operator can be used with a variety of data types, including integers, floating-point numbers, and strings.",
    "=": "'Equal to' is an operator used to compare two values and return a Boolean value of true or false depending on whether the values are equal. The operator can be used with a variety of data types, including integers, floating-point numbers, and strings.",
    "!=": "'Not equal to' is an operator used to compare two values and return a Boolean value of true or false depending on whether the values are not equal. The operator can be used with a variety of data types, including integers, floating-point numbers, and strings.",
    "<=": "'Less than or equal to' is an operator used to compare two values and return a Boolean value of true or false depending on whether the left operand is less than or equal to the right operand. The operator can be used with a variety of data types, including integers, floating-point numbers, and strings.",
    ">=": "'Greater than or equal to' is an operator used to compare two values and return a Boolean value of true or false depending on whether the left operand is greater than or equal to the right operand. The operator can be used with a variety of data types, including integers, floating-point numbers, and strings.",
    count: "Count is an aggregation function that is used to calculate the total number of rows or records in a table or query result. It is a basic function that can be applied to any column in a table, including those containing numerical or non-numerical data.",
    sum: "Sum is an aggregation function that is used to calculate the total sum of values in a given column of a table or query result. It is a mathematical function that can be applied to columns containing numerical data such as integers, floating-point numbers or decimals.",
    avg: "Avg is an aggregation function that is used to calculate the average value of a given column of a table or query result. It is a mathematical function that can be applied to columns containing numerical data such as integers, floating-point numbers or decimals.",
    min: "Min is an aggregation function that is used to calculate the minimum value of a given column of a table or query result. It is a mathematical function that can be applied to columns containing numerical data such as integers, floating-point numbers or decimals.",
    max: "Max is an aggregation function that is used to calculate the maximum value of a given column of a table or query result. It is a mathematical function that can be applied to columns containing numerical data such as integers, floating-point numbers or decimals.",
    Group: "Group is a function that is used to group data based on one or more columns in a table or query result. The function allows for the creation of subgroups within the larger data set based on the values in one or more columns.",
    Order: "Order is a function that is used to sort data in a table or query result based on the values in one or more columns. The function allows for the sorting of data in ascending or descending order based on the values in one or more columns.",
    EXISTS: "Exists function is used to test for the existence of a row in a subquery. It is a Boolean function that returns true if the subquery returns any rows, and false otherwise.",
    "NOT EXISTS":
        "Not Exists function is used to test for the non-existence of a row in a subquery. It is a Boolean function that returns true if the subquery returns no rows, and false otherwise.",
    IN: "In is an operator used to test whether a value is in a list of values. It is a Boolean operator that returns true if the value is in the list of values, and false otherwise.",
    "NOT IN":
        "Not In is an operator used to test whether a value is not in a list of values. It is a Boolean operator that returns true if the value is not in the list of values, and false otherwise.",
};
