import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import AWS from "aws-sdk";
import React, { useState, useEffect } from "react";

AWS.config.update({
    region: "us-east-1",
    accessKeyId: "AKIAYRRBYHW4EQTXXL75",
    secretAccessKey: "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",
    sslEnabled: true,
});

const endpoint = "https://mturk-requester-sandbox.us-east-1.amazonaws.com";

// Uncomment this line to use in production
// const endpoint = 'https://mturk-requester.us-east-1.amazonaws.com';
const mTurkClient = new AWS.MTurk({ endpoint: endpoint });

const Home: NextPage = () => {
    const [balance, setBalance] = useState(-1);

    useEffect(() => {
        mTurkClient.getAccountBalance((err, data) => {
            if (err) {
                console.warn("Error making the mTurk API call:", err);
            } else {
                console.log("The call was a success:", data);
                // The call was a success
                const balanceTmp = data.AvailableBalance;
                setBalance(balanceTmp);
            }
        });
    }, []);

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <p> The balance is {balance} </p>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>

                <p className={styles.description}>
                    Get started by editing <code className={styles.code}>pages/index.tsx</code>
                </p>

                <div className={styles.grid}>
                    <a href="https://nextjs.org/docs" className={styles.card}>
                        <h2>Documentation &rarr;</h2>
                        <p>Find in-depth information about Next.js features and API.</p>
                    </a>

                    <a href="https://nextjs.org/learn" className={styles.card}>
                        <h2>Learn &rarr;</h2>
                        <p>Learn about Next.js in an interactive course with quizzes!</p>
                    </a>

                    <a href="https://github.com/vercel/next.js/tree/canary/examples" className={styles.card}>
                        <h2>Examples &rarr;</h2>
                        <p>Discover and deploy boilerplate example Next.js projects.</p>
                    </a>

                    <a
                        href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        className={styles.card}
                    >
                        <h2>Deploy &rarr;</h2>
                        <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
                    </a>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    );
};

export default Home;
