SELECT AVG(O_cars_data.Year), MIN(O_cars_data.Weight) FROM cars_data O_cars_data WHERE (SELECT cars_data.Horsepower, I_car_names.MakeId FROM car_names I_car_names JOIN cars_data I_cars_data ON I_car_names.MakeId=I_cars_data.Id WHERE (O_cars_data.Cylinders = I_cars_data.Cylinders AND I_cars_data.Year > 1970.0) GROUP BY cars_data.Horsepower) < 335.0
SELECT cars_data.Edispl, COUNT(*) FROM cars_data O_cars_data WHERE (O_cars_data.Edispl IN (SELECT cars_data.Horsepower, I_cars_data.Edispl FROM cars_data I_cars_data WHERE (O_cars_data.MPG = I_cars_data.MPG AND (I_cars_data.Weight != 3850.0 AND I_cars_data.Weight != 3433.0)) GROUP BY cars_data.Horsepower HAVING (AVG(cars_data.MPG) > 38.0 OR (AVG(cars_data.Year) != 1982.0 OR cars_data.Horsepower <= 63.0))) AND O_cars_data.Weight = 2123.0) GROUP BY cars_data.Edispl ORDER BY AVG(cars_data.Accelerate)
SELECT * FROM car_names O_car_names WHERE ((O_car_names.Model IN "('ford','chevrolet','chrysler')" AND (SELECT cars_data.Year, I_car_names.Make FROM car_names I_car_names JOIN model_list I_model_list ON I_model_list.Model=I_car_names.Model WHERE (O_car_names.Model = I_car_names.Model AND I_model_list.Model != "'jeep'") GROUP BY cars_data.Year ORDER BY SUM(model_list.Maker) LIMIT 4) != "bmw 320i") OR O_car_names.MakeId = 393.0)
SELECT countries.CountryId, COUNT(DISTINCT O_countries.CountryName) FROM countries O_countries WHERE (O_countries.CountryId = 1.0 AND (O_countries.CountryName = "usa" OR (SELECT cars_data.Weight, I_countries.Continent FROM car_makers I_car_makers JOIN countries I_countries ON I_countries.CountryId=I_car_makers.Country WHERE (O_countries.CountryId = I_countries.CountryId AND I_car_makers.Country != 1.0) GROUP BY cars_data.Weight HAVING cars_data.Weight > 1835.0 ORDER BY model_list.Model LIMIT 4) != 3.0)) GROUP BY countries.CountryId HAVING (SUM(countries.Continent) > 2.0 OR COUNT(countries.CountryName) < 3)
SELECT countries.CountryId, COUNT(DISTINCT O_countries.CountryName) FROM continents O_continents JOIN countries O_countries ON O_continents.ContId=O_countries.Continent WHERE (O_continents.Continent = (SELECT I_continents.Continent FROM continents I_continents JOIN countries I_countries ON I_continents.ContId=I_countries.Continent WHERE (O_countries.Continent = I_countries.Continent AND I_countries.CountryName NOT IN "('australia','france','new zealand','usa')") ORDER BY countries.CountryId LIMIT 1) AND (O_continents.Continent IN "('america','europe')" OR O_countries.CountryName = "usa")) GROUP BY countries.CountryId ORDER BY continents.Continent LIMIT 4
SELECT * FROM model_list O_model_list WHERE (O_model_list.ModelId != (SELECT I_model_list.ModelId FROM model_list I_model_list WHERE (O_model_list.Maker = I_model_list.Maker AND I_model_list.Model LIKE "datsun%")) OR O_model_list.Model NOT IN "('volkswagen','pontiac')") ORDER BY model_list.Model
SELECT model_list.Maker, COUNT(DISTINCT O_car_makers.FullName), COUNT(DISTINCT O_car_makers.Maker) FROM car_makers O_car_makers JOIN countries O_countries ON O_countries.CountryId=O_car_makers.Country WHERE (O_countries.Continent = 3.0 OR (O_car_makers.Country >= (SELECT I_car_makers.Country FROM car_makers I_car_makers WHERE (O_countries.CountryId = I_countries.CountryId AND I_car_makers.Maker != "mazda") ORDER BY car_makers.Country) AND O_car_makers.Maker = "amc")) GROUP BY model_list.Maker
SELECT O_cars_data.Weight FROM cars_data O_cars_data WHERE O_cars_data.Accelerate IN (SELECT I_cars_data.Accelerate FROM cars_data I_cars_data WHERE (O_cars_data.Cylinders = I_cars_data.Cylinders AND (I_cars_data.Year != 1973.0 OR I_cars_data.Id = 244.0))) ORDER BY car_names.Model LIMIT 2
SELECT AVG(O_cars_data.Year) FROM cars_data O_cars_data WHERE ((O_cars_data.Year >= 1982.0 OR O_cars_data.Weight IN (SELECT I_cars_data.Weight FROM car_makers I_car_makers JOIN car_names I_car_names JOIN cars_data I_cars_data JOIN model_list I_model_list ON I_car_makers.Id=I_model_list.Maker AND I_car_names.MakeId=I_cars_data.Id AND I_model_list.Model=I_car_names.Model WHERE (O_cars_data.Id = I_cars_data.Id AND (I_cars_data.Year != 1973.0 OR (I_cars_data.Year >= 1980.0 OR I_car_makers.Country != 1.0))))) OR O_cars_data.Edispl >= 97.0) ORDER BY cars_data.Edispl
SELECT O_car_makers.Id, O_car_makers.Country FROM car_makers O_car_makers WHERE (SELECT I_car_makers.Country FROM car_makers I_car_makers JOIN car_names I_car_names JOIN cars_data I_cars_data JOIN model_list I_model_list ON I_car_makers.Id=I_model_list.Maker AND I_car_names.MakeId=I_cars_data.Id AND I_model_list.Model=I_car_names.Model WHERE (O_car_makers.Maker = I_car_makers.Maker AND (I_cars_data.Id != 221.0 AND I_cars_data.Horsepower >= 95.0)) ORDER BY model_list.Maker LIMIT 3) != 6.0 ORDER BY car_makers.Id
