SELECT stadium.Capacity, MIN(stadium.Highest) FROM stadium WHERE (stadium.Location LIKE "%Ayr%" OR stadium.Name LIKE "Somerse%") GROUP BY stadium.Capacity HAVING (stadium.Capacity > 3808.0 AND (AVG(stadium.Stadium_ID) >= 5.0 AND SUM(stadium.Highest) <= 1125.0))
SELECT singer_in_concert.concert_ID, COUNT(DISTINCT concert.Year), AVG(singer.Singer_ID) FROM concert JOIN singer JOIN singer_in_concert JOIN stadium ON concert.concert_ID=singer_in_concert.concert_ID AND singer.Singer_ID=singer_in_concert.Singer_ID AND stadium.Stadium_ID=concert.Stadium_ID WHERE (stadium.Name != "Bayview Stadium" OR concert.Theme = "Wide Awake") GROUP BY singer_in_concert.concert_ID HAVING ((MIN(stadium.Stadium_ID) <= 2.0 OR COUNT(stadium.Highest) <= 1) AND MAX(stadium.Highest) <= 2363.0)
SELECT concert.Theme, COUNT(*) FROM stadium WHERE (stadium.Highest > 921.0 AND stadium.Lowest != 1294.0) GROUP BY concert.Theme HAVING ((concert.Theme != "Happy Tonight" OR COUNT(stadium.Capacity) = 2) AND COUNT(concert.Year) = 2)
SELECT singer.Singer_ID, COUNT(DISTINCT singer.Song_Name) FROM singer WHERE (singer.Singer_ID != 4 AND (singer.Age < 52 OR singer.Age >= 32)) GROUP BY singer.Singer_ID HAVING (COUNT(singer.Country) <= 2 OR (MAX(singer.Age) > 32 OR singer.Singer_ID = 2))
SELECT stadium.Capacity, MAX(stadium.Capacity) FROM stadium WHERE stadium.Location IN "('Peterhead','East Fife','Queen\'s Park')" GROUP BY stadium.Capacity HAVING MAX(stadium.Stadium_ID) > 2.0
SELECT singer.Country, COUNT(DISTINCT singer.Country) FROM singer WHERE singer.Singer_ID != 4 GROUP BY singer.Country HAVING ((COUNT(singer_in_concert.concert_ID) > 3 AND COUNT(singer.Song_release_year) >= 1) AND MAX(singer_in_concert.concert_ID) < 2.0)
SELECT singer.Is_male, COUNT(*) FROM singer WHERE (singer.Is_male NOT LIKE "T%" AND singer.Country = "Netherlands") GROUP BY singer.Is_male HAVING ((COUNT(singer.Song_release_year) >= 2 OR COUNT(singer.Name) < 4) AND singer.Is_male != "F")
SELECT singer.Age, COUNT(DISTINCT singer.Country), COUNT(DISTINCT singer.Age) FROM singer WHERE (singer.Age > 43 OR (singer.Age < 52 AND singer.Singer_ID = 1)) GROUP BY singer.Age HAVING ((COUNT(singer.Is_male) = 2 OR COUNT(singer.Song_Name) <= 4) AND COUNT(singer.Is_male) = 3)
SELECT concert.Year, COUNT(*) FROM concert JOIN singer JOIN singer_in_concert JOIN stadium ON concert.concert_ID=singer_in_concert.concert_ID AND singer.Singer_ID=singer_in_concert.Singer_ID AND stadium.Stadium_ID=concert.Stadium_ID WHERE (stadium.Average != 1477.0 OR singer.Age != 32) GROUP BY concert.Year HAVING (COUNT(stadium.Lowest) < 4 AND COUNT(concert.Stadium_ID) != 2)
SELECT stadium.Name, COUNT(DISTINCT stadium.Highest) FROM stadium WHERE (stadium.Stadium_ID != 3.0 OR stadium.Average >= 2106.0) GROUP BY stadium.Name HAVING (COUNT(stadium.Location) <= 2 AND SUM(stadium.Stadium_ID) >= 2.0)
SELECT singer.Singer_ID, COUNT(*) FROM singer WHERE (singer.Country IN "('Netherlands','United States','France')" OR (singer.Age > 43 OR singer.Song_Name != "Gentleman")) GROUP BY singer.Singer_ID HAVING (singer.Singer_ID <= 1 OR COUNT(singer.Age) <= 2)
SELECT singer.Age, COUNT(DISTINCT singer.Name), MIN(singer.Singer_ID) FROM singer WHERE (singer.Age != 25 OR singer.Name IN "('Joe Sharp','Timbaland','Tribal King','John Nizinik')") GROUP BY singer.Age HAVING (COUNT(singer.Is_male) >= 1 AND COUNT(singer.Name) < 3)
SELECT singer.Singer_ID, COUNT(DISTINCT singer.Is_male), COUNT(DISTINCT singer.Song_Name) FROM singer WHERE (singer.Age > 32 OR singer.Name != "John Nizinik") GROUP BY singer.Singer_ID HAVING COUNT(singer.Song_Name) > 1
SELECT stadium.Location, COUNT(DISTINCT concert.Year) FROM concert JOIN stadium ON stadium.Stadium_ID=concert.Stadium_ID WHERE (concert.Theme IN "('Wide Awake','Party All Night','Free choice','Free choice 2')" AND (stadium.Location IN "('East Fife','Brechin City')" OR stadium.Capacity <= 11998.0)) GROUP BY stadium.Location HAVING MAX(stadium.Lowest) < 1057.0
SELECT singer.Is_male, MAX(singer.Age) FROM singer WHERE (singer.Singer_ID = 4 AND (singer.Name LIKE "Rose%" AND singer.Country LIKE "%France%")) GROUP BY singer.Is_male HAVING (COUNT(singer.Country) = 4 AND COUNT(singer.Song_Name) < 1)
SELECT stadium.Stadium_ID, AVG(stadium.Lowest), AVG(stadium.Highest) FROM stadium WHERE (stadium.Location LIKE "Peterhe%" AND stadium.Name NOT LIKE "%Somerse%") GROUP BY stadium.Stadium_ID HAVING ((stadium.Stadium_ID != 3.0 AND SUM(stadium.Capacity) != 2000.0) OR MIN(stadium.Highest) != 1980.0)
SELECT singer.Country, AVG(singer.Age), COUNT(DISTINCT singer.Name) FROM singer WHERE singer.Song_Name NOT LIKE "You%" GROUP BY singer.Country HAVING singer.Country NOT IN "("('United States','France')", 2)"
SELECT stadium.Highest, COUNT(DISTINCT stadium.Location), SUM(stadium.Capacity) FROM stadium WHERE (stadium.Lowest != 1057.0 OR stadium.Name NOT IN "('Forthbank Stadium','Balmoor')") GROUP BY stadium.Highest HAVING (COUNT(stadium.Name) <= 1 AND COUNT(stadium.Location) != 2)
SELECT singer.Name, COUNT(DISTINCT singer.Age) FROM singer WHERE (singer.Country NOT LIKE "%United" AND singer.Song_Name = "Dangerous") GROUP BY singer.Name HAVING ((COUNT(singer.Song_Name) > 1 AND COUNT(singer.Song_Name) > 4) OR COUNT(singer.Country) <= 4)
SELECT singer.Country, COUNT(*) FROM singer WHERE singer.Country NOT LIKE "%etherla" GROUP BY singer.Country HAVING (COUNT(singer.Name) > 2 OR COUNT(singer.Name) <= 3)
