SELECT singer.Is_male, COUNT(*) FROM singer O_singer WHERE (O_singer.Age >= 52 AND O_singer.Age < (SELECT singer.Country, SUM(I_singer.Age) FROM singer I_singer GROUP BY singer.Country)) GROUP BY singer.Is_male HAVING MIN(singer.Singer_ID) < 1 ORDER BY COUNT(singer.Song_release_year) LIMIT 3
SELECT stadium.Stadium_ID, COUNT(DISTINCT O_concert.Year) FROM concert O_concert JOIN stadium O_stadium ON O_stadium.Stadium_ID=O_concert.Stadium_ID WHERE (O_stadium.Highest != (SELECT stadium.Highest, AVG(I_stadium.Highest) FROM stadium I_stadium WHERE I_stadium.Highest >= 780.0 GROUP BY stadium.Highest HAVING (MAX(stadium.Average) >= 1477.0 AND (COUNT(stadium.Location) >= 2 AND MAX(stadium.Capacity) >= 11998.0))) OR O_stadium.Name LIKE "%Glebe") GROUP BY stadium.Stadium_ID HAVING (COUNT(concert.concert_Name) != 3 OR MAX(concert.concert_ID) >= 2.0) ORDER BY COUNT(stadium.Location)
SELECT O_concert.Year, O_concert.concert_Name FROM concert O_concert JOIN stadium O_stadium ON O_stadium.Stadium_ID=O_concert.Stadium_ID WHERE (O_stadium.Stadium_ID = 1.0 AND (O_stadium.Location != "Arbroath" OR O_stadium.Capacity <= (SELECT AVG(I_stadium.Capacity) FROM concert I_concert JOIN stadium I_stadium ON I_stadium.Stadium_ID=I_concert.Stadium_ID WHERE I_concert.concert_Name != "Week 2" ORDER BY stadium.Location LIMIT 4)))
SELECT singer_in_concert.concert_ID, AVG(O_stadium.Average), MAX(O_stadium.Highest) FROM concert O_concert JOIN stadium O_stadium ON O_stadium.Stadium_ID=O_concert.Stadium_ID WHERE (O_stadium.Capacity < 11998.0 OR (O_concert.concert_ID >= (SELECT concert.Theme, AVG(I_concert.concert_ID) FROM concert I_concert GROUP BY concert.Theme HAVING concert.Theme NOT IN "("('Party All Night')", 1)" ORDER BY COUNT(concert.Year) LIMIT 2) OR O_stadium.Average >= 1477.0)) GROUP BY singer_in_concert.concert_ID HAVING (SUM(stadium.Highest) = 1057.0 AND COUNT(concert.Year) > 3) ORDER BY SUM(stadium.Stadium_ID)
SELECT stadium.Stadium_ID, COUNT(DISTINCT O_stadium.Name) FROM concert O_concert JOIN singer O_singer JOIN singer_in_concert O_singer_in_concert JOIN stadium O_stadium ON O_concert.concert_ID=O_singer_in_concert.concert_ID AND O_singer.Singer_ID=O_singer_in_concert.Singer_ID AND O_stadium.Stadium_ID=O_concert.Stadium_ID WHERE (O_stadium.Lowest = (SELECT stadium.Stadium_ID, MIN(I_stadium.Lowest) FROM stadium I_stadium WHERE ((I_stadium.Name IN "('Somerset Park','Forthbank Stadium','Bayview Stadium','Recreation Park')" AND I_stadium.Stadium_ID = 2.0) AND I_stadium.Location NOT IN "('Arbroath','Stirling Albion','Queen\'s Park')") GROUP BY stadium.Stadium_ID) OR O_singer.Song_Name NOT IN "('Gentleman','Hey Oh','You')") GROUP BY stadium.Stadium_ID ORDER BY singer_in_concert.Singer_ID
SELECT stadium.Lowest, COUNT(*) FROM stadium O_stadium WHERE ((O_stadium.Capacity <= (SELECT AVG(I_stadium.Capacity) FROM stadium I_stadium) OR O_stadium.Stadium_ID != 1.0) OR O_stadium.Lowest = 411.0) GROUP BY stadium.Lowest HAVING COUNT(stadium.Name) >= 2
SELECT stadium.Lowest, COUNT(DISTINCT O_stadium.Location), COUNT(DISTINCT O_concert.Year) FROM concert O_concert JOIN stadium O_stadium ON O_stadium.Stadium_ID=O_concert.Stadium_ID WHERE O_stadium.Stadium_ID != (SELECT stadium.Location, SUM(I_stadium.Stadium_ID) FROM stadium I_stadium WHERE (I_stadium.Highest > 837.0 OR (I_stadium.Average < 1477.0 OR I_stadium.Stadium_ID != 6.0)) GROUP BY stadium.Location HAVING stadium.Location NOT LIKE "%Raith%") GROUP BY stadium.Lowest HAVING (MAX(stadium.Average) != 615.0 AND COUNT(concert.Theme) >= 1) ORDER BY singer_in_concert.concert_ID LIMIT 1
SELECT concert.Theme, MAX(O_singer_in_concert.concert_ID), COUNT(DISTINCT O_singer.Name) FROM concert O_concert JOIN singer O_singer JOIN singer_in_concert O_singer_in_concert ON O_concert.concert_ID=O_singer_in_concert.concert_ID AND O_singer.Singer_ID=O_singer_in_concert.Singer_ID WHERE (O_singer.Name IN "('Justin Brown','John Nizinik','Joe Sharp','Rose White')" AND O_concert.concert_ID < (SELECT singer.Song_Name, MAX(I_concert.concert_ID) FROM concert I_concert GROUP BY singer.Song_Name HAVING COUNT(concert.Year) > 1 ORDER BY COUNT(singer.Country))) GROUP BY concert.Theme
SELECT * FROM concert O_concert WHERE ((O_concert.Theme NOT IN "('Bleeding Love','Happy Tonight','Free choice 2','Wide Awake')" OR O_concert.concert_ID < (SELECT AVG(I_concert.concert_ID) FROM concert I_concert)) OR O_concert.Theme LIKE "%Tonight") ORDER BY concert.concert_Name LIMIT 3
SELECT stadium.Stadium_ID, COUNT(*) FROM stadium O_stadium WHERE O_stadium.Highest >= (SELECT singer_in_concert.Singer_ID, AVG(I_stadium.Highest) FROM stadium I_stadium GROUP BY singer_in_concert.Singer_ID HAVING (COUNT(concert.concert_Name) <= 1 AND COUNT(concert.Stadium_ID) <= 3) ORDER BY stadium.Average) GROUP BY stadium.Stadium_ID HAVING (COUNT(stadium.Location) >= 1 OR AVG(stadium.Lowest) <= 1057.0) ORDER BY COUNT(stadium.Name) LIMIT 2
