SELECT singer.Name, COUNT(DISTINCT singer.Song_release_year) FROM singer WHERE singer.Name != "Justin Brown" GROUP BY singer.Name HAVING ((COUNT(singer.Song_release_year) > 1 AND MIN(singer.Singer_ID) < 1) OR AVG(singer.Singer_ID) <= 1) ORDER BY singer.Song_Name
SELECT stadium.Capacity, COUNT(*) FROM stadium WHERE (stadium.Lowest = 1294.0 AND (stadium.Location IN "('Raith Rovers','Stirling Albion')" OR stadium.Highest < 837.0)) GROUP BY stadium.Capacity HAVING (COUNT(stadium.Average) > 2 OR COUNT(stadium.Name) = 3) ORDER BY stadium.Name
SELECT concert.Theme, COUNT(*) FROM singer WHERE (singer.Age != 52 OR singer.Country != "United States") GROUP BY concert.Theme HAVING COUNT(singer.Country) <= 3 ORDER BY AVG(concert.concert_ID)
SELECT singer.Singer_ID, COUNT(*) FROM singer WHERE singer.Name = "Timbaland" GROUP BY singer.Singer_ID HAVING (COUNT(singer.Song_Name) = 2 AND COUNT(singer.Song_release_year) = 2) ORDER BY AVG(singer.Age)
SELECT stadium.Average, COUNT(DISTINCT singer_in_concert.Singer_ID) FROM concert JOIN singer_in_concert JOIN stadium ON concert.concert_ID=singer_in_concert.concert_ID AND stadium.Stadium_ID=concert.Stadium_ID WHERE (concert.concert_ID != 3.0 AND stadium.Name LIKE "Recreat%") GROUP BY stadium.Average HAVING (MIN(stadium.Stadium_ID) < 2.0 AND COUNT(singer.Name) != 1) ORDER BY COUNT(stadium.Capacity)
SELECT stadium.Capacity, COUNT(*) FROM stadium WHERE (stadium.Stadium_ID = 5.0 OR stadium.Highest > 1980.0) GROUP BY stadium.Capacity HAVING MAX(stadium.Stadium_ID) > 2.0 ORDER BY stadium.Highest
SELECT singer.Country, COUNT(DISTINCT singer.Country) FROM singer WHERE singer.Singer_ID != 4 GROUP BY singer.Country HAVING ((COUNT(singer_in_concert.concert_ID) > 3 AND COUNT(singer.Song_release_year) >= 1) AND MAX(singer_in_concert.concert_ID) < 5.0) ORDER BY COUNT(singer.Is_male)
SELECT stadium.Highest, AVG(stadium.Highest), AVG(stadium.Stadium_ID) FROM stadium WHERE (stadium.Stadium_ID != 9.0 AND stadium.Location IN "('Stirling Albion','Alloa Athletic')") GROUP BY stadium.Highest HAVING (COUNT(stadium.Capacity) <= 2 OR (stadium.Highest != 780.0 AND AVG(stadium.Capacity) > 3960.0)) ORDER BY stadium.Highest
SELECT concert.Year, SUM(singer_in_concert.concert_ID) FROM concert JOIN singer_in_concert JOIN stadium ON concert.concert_ID=singer_in_concert.concert_ID AND stadium.Stadium_ID=concert.Stadium_ID WHERE (stadium.Stadium_ID = 6.0 OR (concert.concert_Name NOT IN "('Week 1','Auditions')" AND stadium.Location != "Arbroath")) GROUP BY concert.Year HAVING (concert.Year = "2015.0" OR (COUNT(concert.Theme) != 4 AND COUNT(singer_in_concert.Singer_ID) = 2)) ORDER BY concert.concert_ID
SELECT stadium.Stadium_ID, COUNT(DISTINCT stadium.Location), COUNT(DISTINCT concert.Theme) FROM concert JOIN stadium ON stadium.Stadium_ID=concert.Stadium_ID WHERE stadium.Location NOT LIKE "Raith%" GROUP BY stadium.Stadium_ID HAVING (SUM(singer_in_concert.concert_ID) < 2.0 AND (COUNT(stadium.Name) >= 2 OR MAX(stadium.Highest) >= 2363.0)) ORDER BY COUNT(concert.Stadium_ID)
SELECT singer.Singer_ID, COUNT(*) FROM singer WHERE singer.Is_male != "'T'" GROUP BY singer.Singer_ID HAVING (singer.Singer_ID <= 1 OR COUNT(singer.Is_male) < 4) ORDER BY MAX(singer.Age)
SELECT singer.Song_Name, COUNT(DISTINCT singer.Is_male) FROM singer WHERE singer.Country IN "('France','United States','Netherlands')" GROUP BY singer.Song_Name HAVING ((COUNT(singer.Song_release_year) != 2 OR COUNT(singer.Country) != 1) AND COUNT(singer.Name) != 1) ORDER BY COUNT(singer.Is_male)
SELECT stadium.Highest, COUNT(DISTINCT stadium.Location) FROM stadium WHERE (stadium.Capacity <= 52500.0 AND (stadium.Capacity != 10104.0 OR stadium.Capacity <= 11998.0)) GROUP BY stadium.Highest HAVING (stadium.Highest != 921.0 OR (COUNT(stadium.Name) != 3 AND MIN(stadium.Lowest) > 411.0)) ORDER BY stadium.Average
SELECT concert.concert_Name, COUNT(DISTINCT concert.Year) FROM concert WHERE concert.Theme = "Free choice 2" GROUP BY concert.concert_Name HAVING (COUNT(concert.concert_ID) <= 2 AND (COUNT(concert.Stadium_ID) > 1 AND COUNT(concert.Theme) != 4)) ORDER BY concert.Year
SELECT stadium.Average, COUNT(DISTINCT stadium.Name) FROM stadium WHERE ((stadium.Name NOT LIKE "Balmoor%" OR stadium.Average >= 1477.0) AND stadium.Stadium_ID != 5.0) GROUP BY stadium.Average HAVING (COUNT(stadium.Name) = 4 AND MAX(stadium.Capacity) = 52500.0) ORDER BY stadium.Name
SELECT singer.Country, COUNT(*) FROM singer WHERE (singer.Country != "United States" AND singer.Song_Name NOT IN "('Love','Dangerous','Hey Oh','You')") GROUP BY singer.Country HAVING ((MIN(singer.Age) >= 52 OR singer.Country NOT LIKE "%Netherl") OR MAX(singer.Singer_ID) > 1) ORDER BY singer.Singer_ID
SELECT singer.Country, SUM(singer.Singer_ID) FROM singer WHERE (singer.Song_Name IN "('Hey Oh','Gentleman','Dangerous','Sun')" OR singer.Country LIKE "France%") GROUP BY singer.Country HAVING (COUNT(singer.Name) != 2 AND (COUNT(singer.Age) < 4 OR AVG(singer.Age) != 52)) ORDER BY singer.Age
SELECT stadium.Location, COUNT(DISTINCT concert.concert_Name) FROM concert JOIN singer_in_concert ON concert.concert_ID=singer_in_concert.concert_ID WHERE singer_in_concert.concert_ID != 2.0 GROUP BY stadium.Location HAVING ((MAX(singer.Age) <= 32 AND COUNT(singer.Country) > 1) AND COUNT(concert.Year) > 1) ORDER BY AVG(concert.concert_ID)
SELECT stadium.Name, MAX(stadium.Lowest) FROM stadium WHERE (stadium.Location = "Peterhead" OR stadium.Location = "Peterhead") GROUP BY stadium.Name HAVING stadium.Name IN "("('Balmoor','Bayview Stadium','Glebe Park')", 3)" ORDER BY stadium.Average
SELECT concert.concert_Name, COUNT(*) FROM concert JOIN singer JOIN singer_in_concert ON concert.concert_ID=singer_in_concert.concert_ID AND singer.Singer_ID=singer_in_concert.Singer_ID WHERE (singer.Song_Name != "Sun" AND concert.Theme LIKE "%Night") GROUP BY concert.concert_Name HAVING ((COUNT(singer.Song_release_year) = 4 OR COUNT(singer.Name) = 1) OR COUNT(concert.Theme) < 3) ORDER BY COUNT(concert.Theme)
