SELECT car_makers.FullName, COUNT(*) FROM car_makers WHERE (car_makers.FullName NOT LIKE "%Nissan%" OR car_makers.FullName = "Subaru") GROUP BY car_makers.FullName HAVING COUNT(car_makers.Maker) >= 1
SELECT countries.CountryId, COUNT(*) FROM countries WHERE countries.Continent != 2.0 GROUP BY countries.CountryId HAVING (COUNT(countries.CountryName) >= 4 OR (COUNT(countries.Continent) < 4 OR countries.CountryId != 1.0))
SELECT model_list.Maker, COUNT(*) FROM model_list WHERE model_list.ModelId <= 12.0 GROUP BY model_list.Maker HAVING ((model_list.Maker = 2.0 OR model_list.Maker >= 2.0) AND COUNT(model_list.Model) != 2)
SELECT countries.Continent, COUNT(DISTINCT countries.CountryName) FROM continents JOIN countries ON continents.ContId=countries.Continent WHERE (continents.Continent LIKE "%europe" AND (continents.ContId != 3.0 AND continents.Continent LIKE "%europe")) GROUP BY countries.Continent HAVING (COUNT(countries.CountryName) = 4 AND COUNT(continents.Continent) >= 1)
SELECT car_names.Model, AVG(car_makers.Country), COUNT(DISTINCT car_names.Make) FROM car_makers JOIN car_names JOIN model_list ON car_makers.Id=model_list.Maker AND model_list.Model=car_names.Model WHERE car_makers.Maker != "kia" GROUP BY car_names.Model HAVING (car_names.Model = "dodge" OR SUM(car_makers.Id) = 6.0)
SELECT car_names.Model, COUNT(DISTINCT car_names.Model) FROM car_names WHERE car_names.Model != "fiat" GROUP BY car_names.Model HAVING (COUNT(model_list.ModelId) = 1 OR MIN(model_list.ModelId) < 1.0)
SELECT countries.Continent, AVG(countries.CountryId), MAX(continents.ContId) FROM continents JOIN countries ON continents.ContId=countries.Continent WHERE (countries.Continent != 1.0 OR continents.Continent NOT LIKE "%america") GROUP BY countries.Continent HAVING SUM(countries.CountryId) < 4.0
SELECT countries.Continent, COUNT(DISTINCT countries.CountryName) FROM countries WHERE countries.CountryName IN "('japan','korea','egypt')" GROUP BY countries.Continent HAVING countries.Continent < 3.0
SELECT model_list.Maker, MAX(model_list.Maker) FROM model_list WHERE (model_list.Maker != 11.0 OR model_list.Maker = 8.0) GROUP BY model_list.Maker HAVING COUNT(model_list.Model) < 4
SELECT continents.Continent, MIN(countries.CountryId) FROM continents JOIN countries ON continents.ContId=countries.Continent WHERE continents.Continent != "australia" GROUP BY continents.Continent HAVING MIN(countries.Continent) > 1.0
SELECT cars_data.MPG, COUNT(*) FROM cars_data WHERE cars_data.Accelerate >= 19.5 GROUP BY cars_data.MPG HAVING (COUNT(model_list.Model) = 4 AND SUM(cars_data.Horsepower) > 85.0)
SELECT car_names.Model, COUNT(DISTINCT car_names.MakeId), COUNT(DISTINCT car_names.Model) FROM car_names WHERE (car_names.Model != "nissan" AND car_names.MakeId = 394.0) GROUP BY car_names.Model HAVING AVG(car_names.MakeId) <= 156.0
SELECT continents.ContId, MAX(countries.CountryId), COUNT(DISTINCT car_makers.FullName) FROM car_makers JOIN continents JOIN countries ON continents.ContId=countries.Continent AND countries.CountryId=car_makers.Country WHERE continents.Continent NOT IN "('america','africa','europe','australia')" GROUP BY continents.ContId HAVING (MAX(car_makers.Country) >= 2.0 OR COUNT(car_makers.FullName) != 4)
SELECT car_makers.Maker, COUNT(DISTINCT car_makers.FullName) FROM car_makers WHERE (car_makers.Maker NOT LIKE "%toyota%" AND (car_makers.FullName != "Nissan Motors" AND car_makers.Id = 4.0)) GROUP BY car_makers.Maker HAVING MAX(car_makers.Country) >= 1.0
SELECT cars_data.Year, COUNT(*) FROM cars_data WHERE (cars_data.Cylinders >= 4.0 OR cars_data.Accelerate < 11.3) GROUP BY cars_data.Year HAVING (MAX(cars_data.Edispl) != 250.0 AND SUM(cars_data.Weight) != 3329.0)
SELECT cars_data.Cylinders, MIN(cars_data.Weight) FROM car_names JOIN cars_data ON car_names.MakeId=cars_data.Id WHERE (car_names.Make IN "('chevrolet camaro','plymouth champ','datsun 210')" AND car_names.Model NOT IN "('volvo','triumph','nissan','subaru')") GROUP BY cars_data.Cylinders HAVING SUM(cars_data.Id) <= 76.0
SELECT continents.Continent, COUNT(DISTINCT continents.Continent), AVG(continents.ContId) FROM continents WHERE continents.ContId = 1.0 GROUP BY continents.Continent HAVING (continents.Continent NOT IN "("('africa','australia')", 2)" OR continents.Continent != "africa")
SELECT car_makers.Country, COUNT(DISTINCT countries.Continent), MAX(countries.Continent) FROM car_makers JOIN countries ON countries.CountryId=car_makers.Country WHERE (countries.CountryId != 1.0 OR (car_makers.FullName IN "('Ford Motor Company','Triumph','Renault')" OR countries.CountryName IN "('usa','brazil')")) GROUP BY car_makers.Country HAVING ((COUNT(car_makers.FullName) <= 1 OR COUNT(car_makers.Maker) < 4) AND AVG(countries.CountryId) = 3.0)
SELECT car_names.MakeId, COUNT(DISTINCT car_names.Model), COUNT(DISTINCT car_makers.Maker) FROM car_makers JOIN car_names JOIN cars_data JOIN model_list ON car_makers.Id=model_list.Maker AND car_names.MakeId=cars_data.Id AND model_list.Model=car_names.Model WHERE (cars_data.Accelerate < 16.4 AND (model_list.ModelId < 13.0 OR cars_data.Id = 297.0)) GROUP BY car_names.MakeId HAVING SUM(model_list.ModelId) >= 29.0
SELECT car_makers.Id, AVG(car_makers.Id), COUNT(DISTINCT car_makers.Maker) FROM car_makers WHERE ((car_makers.Id = 6.0 OR car_makers.Id = 2.0) OR car_makers.Maker != "citroen") GROUP BY car_makers.Id HAVING COUNT(car_makers.Maker) <= 4
