SELECT AVG(O_cars_data.Year), MIN(O_cars_data.Weight) FROM cars_data O_cars_data WHERE O_cars_data.Cylinders IN (SELECT countries.CountryName, I_cars_data.Cylinders FROM car_names I_car_names JOIN cars_data I_cars_data JOIN model_list I_model_list ON I_car_names.MakeId=I_cars_data.Id AND I_model_list.Model=I_car_names.Model WHERE I_model_list.Maker = 1.0 GROUP BY countries.CountryName ORDER BY MAX(cars_data.Weight))
SELECT model_list.Model, AVG(O_model_list.Maker) FROM model_list O_model_list WHERE (O_model_list.Model IN "('ford','volvo')" AND O_model_list.Model IN (SELECT model_list.Model, I_model_list.Model FROM model_list I_model_list GROUP BY model_list.Model HAVING (MAX(cars_data.MPG) < 18.0 OR (COUNT(car_makers.FullName) > 3 OR COUNT(car_names.Model) = 4)) ORDER BY MIN(car_makers.Id) LIMIT 1)) GROUP BY model_list.Model ORDER BY model_list.Model LIMIT 2
SELECT model_list.ModelId, COUNT(DISTINCT O_model_list.Maker), COUNT(DISTINCT O_model_list.ModelId) FROM model_list O_model_list WHERE (O_model_list.ModelId <= 25.0 AND O_model_list.Model != (SELECT I_model_list.Model FROM car_makers I_car_makers JOIN model_list I_model_list ON I_car_makers.Id=I_model_list.Maker WHERE ((I_model_list.Maker != 4.0 AND I_car_makers.Maker IN "('ford','bmw','fiat','amc')") OR I_car_makers.Maker NOT IN "('daimler benz','bmw')"))) GROUP BY model_list.ModelId ORDER BY model_list.Maker LIMIT 2
SELECT * FROM continents O_continents WHERE O_continents.ContId IN (SELECT countries.CountryId, I_continents.ContId FROM continents I_continents GROUP BY countries.CountryId ORDER BY MAX(car_makers.Id)) ORDER BY continents.ContId
SELECT O_cars_data.Horsepower, O_cars_data.Accelerate FROM cars_data O_cars_data WHERE (O_cars_data.Weight < 4746.0 AND O_cars_data.Cylinders IN (SELECT car_names.MakeId, I_cars_data.Cylinders FROM cars_data I_cars_data WHERE (I_cars_data.Horsepower != 69.0 AND I_cars_data.Id = 70.0) GROUP BY car_names.MakeId))
SELECT model_list.Model, COUNT(DISTINCT O_model_list.Model) FROM car_makers O_car_makers JOIN model_list O_model_list ON O_car_makers.Id=O_model_list.Maker WHERE (O_car_makers.Id = 2.0 OR O_car_makers.Maker NOT IN (SELECT I_car_makers.Maker FROM car_makers I_car_makers WHERE I_car_makers.Maker NOT IN "('ford','hyundai','triumph','daimler benz')" ORDER BY car_makers.Country)) GROUP BY model_list.Model
SELECT O_countries.Continent, O_countries.CountryId FROM countries O_countries WHERE O_countries.Continent < (SELECT I_countries.Continent FROM car_makers I_car_makers JOIN countries I_countries ON I_countries.CountryId=I_car_makers.Country WHERE (I_countries.CountryName IN "('france','mexico')" AND (I_car_makers.Id != 15.0 AND I_countries.CountryName NOT IN "('sweden','germany','egypt','mexico')")))
SELECT countries.CountryId, AVG(O_countries.Continent) FROM countries O_countries WHERE O_countries.CountryName != (SELECT I_countries.CountryName FROM countries I_countries ORDER BY countries.CountryId) GROUP BY countries.CountryId ORDER BY countries.CountryId
SELECT O_car_names.MakeId, O_cars_data.Id FROM car_names O_car_names JOIN cars_data O_cars_data ON O_car_names.MakeId=O_cars_data.Id WHERE ((O_car_names.Make != (SELECT I_car_names.Make FROM car_names I_car_names JOIN cars_data I_cars_data ON I_car_names.MakeId=I_cars_data.Id WHERE (I_cars_data.MPG <= 14.0 AND I_car_names.Make != "plymouth fury") ORDER BY cars_data.Horsepower) AND O_cars_data.Cylinders < 4.0) AND O_car_names.Make IN "('mazda rx-4','audi 4000','oldsmobile delta 88 royale','dodge coronet brougham','pontiac firebird')") ORDER BY cars_data.Year LIMIT 1
SELECT O_continents.Continent, O_continents.ContId FROM continents O_continents WHERE (O_continents.ContId IN (SELECT continents.Continent, I_continents.ContId FROM continents I_continents GROUP BY continents.Continent) AND O_continents.Continent != "europe") ORDER BY countries.Continent
