SELECT AVG(O_model_list.Maker), MIN(O_car_makers.Country) FROM car_makers O_car_makers JOIN model_list O_model_list ON O_car_makers.Id=O_model_list.Maker WHERE (SELECT MAX(I_continents.ContId) FROM continents I_continents JOIN countries I_countries ON I_continents.ContId=I_countries.Continent WHERE (O_car_makers.Id = I_car_makers.Id AND I_countries.Continent != 2.0)) < 3.0
SELECT * FROM car_names O_car_names WHERE (((SELECT MAX(I_car_names.MakeId) FROM car_names I_car_names JOIN cars_data I_cars_data ON I_car_names.MakeId=I_cars_data.Id WHERE (O_car_names.Model = I_car_names.Model AND I_cars_data.MPG != 13.0)) <= 383.0 OR O_car_names.Model IN "('toyota','triumph')") OR O_car_names.Make NOT LIKE "hevrole%")
SELECT * FROM cars_data O_cars_data WHERE (O_cars_data.Weight >= 2542.0 AND (SELECT COUNT(I_cars_data.Accelerate) FROM cars_data I_cars_data WHERE (O_cars_data.Horsepower = I_cars_data.Horsepower AND I_cars_data.Weight > 4166.0)) < 8)
SELECT O_countries.CountryName, O_countries.CountryId FROM countries O_countries WHERE (SELECT COUNT(I_countries.CountryName) FROM car_makers I_car_makers JOIN countries I_countries ON I_countries.CountryId=I_car_makers.Country WHERE (O_countries.Continent = I_countries.Continent AND (I_countries.CountryName IN "('usa','russia','france','uk')" OR I_car_makers.Country = 1.0))) = 603
SELECT O_car_makers.Maker, O_car_makers.Country FROM car_makers O_car_makers WHERE (SELECT SUM(I_car_makers.Country) FROM car_makers I_car_makers JOIN countries I_countries ON I_countries.CountryId=I_car_makers.Country WHERE (O_car_makers.Id = I_car_makers.Id AND I_countries.CountryName IN "('usa','nigeria')")) > 160.0
SELECT * FROM cars_data O_cars_data WHERE (O_cars_data.Cylinders != 3.0 OR (SELECT COUNT(I_cars_data.Id) FROM car_names I_car_names JOIN cars_data I_cars_data ON I_car_names.MakeId=I_cars_data.Id WHERE (O_cars_data.Year = I_cars_data.Year AND I_car_names.Model LIKE "%evrolet")) < 12)
SELECT MIN(O_continents.ContId), COUNT(DISTINCT O_continents.Continent) FROM continents O_continents WHERE (SELECT COUNT(I_continents.Continent) FROM continents I_continents JOIN countries I_countries ON I_continents.ContId=I_countries.Continent WHERE (O_continents.ContId = I_continents.ContId AND (I_countries.CountryName IN "('usa','germany','sweden','russia')" AND (I_countries.Continent = 1.0 AND I_countries.CountryId = 1.0)))) = 603
SELECT O_cars_data.Weight FROM cars_data O_cars_data WHERE ((SELECT SUM(I_cars_data.Cylinders) FROM cars_data I_cars_data WHERE (O_cars_data.Weight = I_cars_data.Weight AND I_cars_data.Cylinders != 8.0)) <= 36.0 AND O_cars_data.Cylinders != 4.0)
SELECT O_car_names.Model FROM car_names O_car_names WHERE (O_car_names.MakeId > (SELECT MIN(I_car_names.MakeId) FROM car_names I_car_names JOIN cars_data I_cars_data JOIN model_list I_model_list ON I_car_names.MakeId=I_cars_data.Id AND I_model_list.Model=I_car_names.Model WHERE (O_car_names.Make = I_car_names.Make AND ((I_model_list.Model = "datsun" OR I_cars_data.MPG <= 28.0) OR I_cars_data.Edispl = 250.0))) OR O_car_names.Model NOT IN "('capri','audi','pontiac')")
SELECT O_countries.CountryName FROM countries O_countries WHERE ((SELECT MIN(I_countries.CountryId) FROM car_makers I_car_makers JOIN countries I_countries JOIN model_list I_model_list ON I_car_makers.Id=I_model_list.Maker AND I_countries.CountryId=I_car_makers.Country WHERE (O_countries.Continent = I_countries.Continent AND I_model_list.Model NOT LIKE "%subaru")) >= 1.0 OR O_countries.CountryId != 1.0)
