SELECT stadium.Capacity, MIN(stadium.Highest) FROM stadium WHERE (stadium.Location LIKE "%Ayr%" OR stadium.Name LIKE "Somerse%") GROUP BY stadium.Capacity
SELECT stadium.Lowest, COUNT(*) FROM concert JOIN singer_in_concert JOIN stadium ON concert.concert_ID=singer_in_concert.concert_ID AND stadium.Stadium_ID=concert.Stadium_ID WHERE (singer_in_concert.concert_ID != 2.0 AND (stadium.Highest != 4812.0 OR stadium.Lowest < 533.0)) GROUP BY stadium.Lowest
SELECT concert.Stadium_ID, COUNT(DISTINCT singer.Song_Name), COUNT(DISTINCT concert.concert_ID) FROM concert JOIN singer JOIN singer_in_concert ON concert.concert_ID=singer_in_concert.concert_ID AND singer.Singer_ID=singer_in_concert.Singer_ID WHERE (singer.Singer_ID != 4 AND singer.Is_male != "T") GROUP BY concert.Stadium_ID
SELECT stadium.Average, COUNT(*) FROM stadium WHERE (stadium.Average >= 615.0 OR stadium.Average != 730.0) GROUP BY stadium.Average
SELECT stadium.Lowest, AVG(stadium.Capacity) FROM stadium WHERE (stadium.Location NOT LIKE "Brechin%" OR stadium.Stadium_ID = 1.0) GROUP BY stadium.Lowest
SELECT singer.Song_release_year, COUNT(DISTINCT singer.Is_male) FROM concert JOIN singer JOIN singer_in_concert JOIN stadium ON concert.concert_ID=singer_in_concert.concert_ID AND singer.Singer_ID=singer_in_concert.Singer_ID AND stadium.Stadium_ID=concert.Stadium_ID WHERE (singer.Singer_ID != 5 AND stadium.Average <= 2106.0) GROUP BY singer.Song_release_year
SELECT singer_in_concert.Singer_ID, COUNT(*) FROM singer_in_concert WHERE (singer_in_concert.concert_ID != 2.0 OR singer_in_concert.concert_ID = 3.0) GROUP BY singer_in_concert.Singer_ID
SELECT singer_in_concert.Singer_ID, COUNT(DISTINCT singer_in_concert.Singer_ID) FROM singer JOIN singer_in_concert ON singer.Singer_ID=singer_in_concert.Singer_ID WHERE singer.Song_Name LIKE "%Love%" GROUP BY singer_in_concert.Singer_ID
SELECT singer_in_concert.Singer_ID, COUNT(DISTINCT singer_in_concert.Singer_ID), COUNT(DISTINCT singer_in_concert.concert_ID) FROM singer_in_concert WHERE singer_in_concert.concert_ID = 5.0 GROUP BY singer_in_concert.Singer_ID
SELECT singer.Age, COUNT(DISTINCT concert.Stadium_ID) FROM concert JOIN singer JOIN singer_in_concert ON concert.concert_ID=singer_in_concert.concert_ID AND singer.Singer_ID=singer_in_concert.Singer_ID WHERE (singer.Is_male = "T" AND (singer.Is_male NOT LIKE "%F%" AND singer.Country NOT LIKE "%France")) GROUP BY singer.Age
SELECT stadium.Location, SUM(stadium.Highest) FROM stadium WHERE (stadium.Location != "Peterhead" OR (stadium.Stadium_ID = 2.0 AND stadium.Location != "Arbroath")) GROUP BY stadium.Location
SELECT stadium.Location, MIN(stadium.Stadium_ID) FROM stadium WHERE (stadium.Average > 637.0 AND stadium.Highest < 1125.0) GROUP BY stadium.Location
SELECT stadium.Average, MAX(stadium.Capacity) FROM stadium WHERE (stadium.Name = "Hampden Park" AND stadium.Capacity >= 52500.0) GROUP BY stadium.Average
SELECT singer.Country, COUNT(*) FROM singer WHERE (singer.Name LIKE "%Nizinik" OR singer.Is_male LIKE "%T") GROUP BY singer.Country
SELECT singer.Age, COUNT(*) FROM singer WHERE (singer.Age != 25 OR singer.Name IN "('Joe Sharp','Timbaland','Tribal King','John Nizinik')") GROUP BY singer.Age
SELECT singer.Singer_ID, COUNT(DISTINCT singer.Is_male), COUNT(DISTINCT singer.Song_Name) FROM singer WHERE (singer.Age > 32 OR singer.Name != "John Nizinik") GROUP BY singer.Singer_ID
SELECT singer.Is_male, MAX(singer.Age) FROM singer WHERE (singer.Country IN "('Netherlands','United States','France')" OR singer.Name IN "('Joe Sharp','John Nizinik')") GROUP BY singer.Is_male
SELECT singer.Song_Name, COUNT(*) FROM stadium WHERE stadium.Lowest < 404.0 GROUP BY singer.Song_Name
SELECT singer_in_concert.concert_ID, SUM(singer_in_concert.concert_ID) FROM singer_in_concert WHERE singer_in_concert.concert_ID = 5.0 GROUP BY singer_in_concert.concert_ID
SELECT singer.Song_release_year, COUNT(*) FROM singer WHERE ((singer.Singer_ID = 1 AND singer.Name NOT IN "('Tribal King','Justin Brown','Timbaland','John Nizinik')") AND singer.Age >= 52) GROUP BY singer.Song_release_year
