SELECT singer.Name, COUNT(DISTINCT singer.Song_release_year) FROM singer WHERE singer.Name != "Justin Brown" GROUP BY singer.Name ORDER BY singer.Song_Name
SELECT concert.concert_ID, COUNT(DISTINCT concert.Year), COUNT(DISTINCT concert.Theme) FROM concert WHERE (concert.Theme != "Party All Night" OR concert.concert_ID != 4.0) GROUP BY concert.concert_ID ORDER BY COUNT(concert.Theme)
SELECT stadium.Average, COUNT(*) FROM singer WHERE singer.Is_male = "T" GROUP BY stadium.Average ORDER BY COUNT(concert.Year)
SELECT singer.Country, COUNT(DISTINCT singer_in_concert.Singer_ID), COUNT(DISTINCT singer.Song_release_year) FROM singer JOIN singer_in_concert ON singer.Singer_ID=singer_in_concert.Singer_ID WHERE ((singer.Name != "Timbaland" OR singer_in_concert.concert_ID = 2.0) AND singer.Age < 52) GROUP BY singer.Country ORDER BY singer.Age
SELECT stadium.Name, COUNT(*) FROM stadium WHERE stadium.Capacity < 4000.0 GROUP BY stadium.Name ORDER BY stadium.Location
SELECT stadium.Stadium_ID, COUNT(*) FROM singer WHERE singer.Singer_ID != 5 GROUP BY stadium.Stadium_ID ORDER BY COUNT(singer.Song_release_year)
SELECT concert.Stadium_ID, AVG(concert.concert_ID), COUNT(DISTINCT concert.concert_ID) FROM concert WHERE concert.concert_ID = 1.0 GROUP BY concert.Stadium_ID ORDER BY COUNT(concert.Theme)
SELECT stadium.Average, SUM(stadium.Highest), COUNT(DISTINCT stadium.Location) FROM stadium WHERE stadium.Lowest >= 400.0 GROUP BY stadium.Average ORDER BY COUNT(stadium.Capacity)
SELECT concert.Year, COUNT(DISTINCT stadium.Location), MAX(stadium.Average) FROM concert JOIN stadium ON stadium.Stadium_ID=concert.Stadium_ID WHERE (stadium.Name NOT IN "('Stark\'s Park','Hampden Park','Balmoor','Somerset Park','Recreation Park')" AND (stadium.Average < 1477.0 AND concert.Theme IN "('Party All Night','Happy Tonight','Bleeding Love','Free choice 2','Wide Awake')")) GROUP BY concert.Year ORDER BY AVG(stadium.Average)
SELECT concert.concert_Name, COUNT(DISTINCT concert.Year) FROM concert WHERE (concert.concert_Name != "Home Visits" OR (concert.concert_ID = 2.0 AND concert.concert_Name != "Super bootcamp")) GROUP BY concert.concert_Name ORDER BY COUNT(singer_in_concert.Singer_ID)
SELECT stadium.Name, MAX(stadium.Stadium_ID) FROM stadium WHERE (stadium.Location IN "('Brechin City','Raith Rovers','Ayr United','Alloa Athletic','Stirling Albion')" AND stadium.Location IN "('Ayr United','Stirling Albion','Raith Rovers','Brechin City','East Fife')") GROUP BY stadium.Name ORDER BY SUM(stadium.Stadium_ID)
SELECT stadium.Name, COUNT(*) FROM stadium WHERE (stadium.Name IN "('Hampden Park','Balmoor','Stark\'s Park','Glebe Park','Recreation Park')" OR (stadium.Lowest > 1294.0 OR stadium.Lowest != 400.0)) GROUP BY stadium.Name ORDER BY stadium.Name
SELECT stadium.Average, COUNT(*) FROM stadium WHERE (stadium.Lowest != 1057.0 OR stadium.Highest != 4812.0) GROUP BY stadium.Average ORDER BY MIN(stadium.Lowest)
SELECT singer.Name, SUM(stadium.Lowest) FROM concert JOIN singer JOIN singer_in_concert JOIN stadium ON concert.concert_ID=singer_in_concert.concert_ID AND singer.Singer_ID=singer_in_concert.Singer_ID AND stadium.Stadium_ID=concert.Stadium_ID WHERE (singer.Age <= 29 OR singer.Name = "John Nizinik") GROUP BY singer.Name ORDER BY AVG(singer_in_concert.concert_ID)
SELECT stadium.Location, SUM(stadium.Highest) FROM stadium WHERE stadium.Name = "Somerset Park" GROUP BY stadium.Location ORDER BY stadium.Highest
SELECT singer.Is_male, COUNT(DISTINCT singer.Singer_ID) FROM singer WHERE (singer.Country LIKE "%France%" OR (singer.Name LIKE "Rose%" OR singer.Country NOT IN "('United States','Netherlands')")) GROUP BY singer.Is_male ORDER BY COUNT(singer.Song_Name)
SELECT singer.Song_release_year, COUNT(DISTINCT singer.Song_Name), SUM(singer.Age) FROM singer WHERE (singer.Age > 29 AND (singer.Name LIKE "%Rose%" OR singer.Song_Name IN "('Sun','Love')")) GROUP BY singer.Song_release_year ORDER BY COUNT(singer.Country)
SELECT stadium.Name, AVG(stadium.Lowest) FROM stadium WHERE (stadium.Stadium_ID = 2.0 OR stadium.Location LIKE "%City") GROUP BY stadium.Name ORDER BY stadium.Lowest
SELECT singer_in_concert.concert_ID, COUNT(*) FROM singer WHERE singer.Name IN "('Joe Sharp','Tribal King','John Nizinik')" GROUP BY singer_in_concert.concert_ID ORDER BY stadium.Highest
SELECT concert.Year, COUNT(DISTINCT concert.concert_Name), COUNT(DISTINCT concert.Year) FROM concert WHERE concert.Theme LIKE "%2" GROUP BY concert.Year ORDER BY stadium.Location
