SELECT stadium.Average, SUM(O_stadium.Average), AVG(O_stadium.Highest) FROM stadium O_stadium WHERE (O_stadium.Highest != 2363.0 AND ((SELECT stadium.Name, I_stadium.Stadium_ID FROM stadium I_stadium WHERE (O_stadium.Average = I_stadium.Average AND ((I_stadium.Location NOT LIKE "%Raith" OR I_stadium.Highest = 2363.0) OR I_stadium.Average >= 2106.0)) GROUP BY stadium.Name) = 1.0 OR O_stadium.Location IN "('Raith Rovers','Stirling Albion')")) GROUP BY stadium.Average ORDER BY stadium.Location
SELECT O_concert.Theme FROM concert O_concert WHERE O_concert.concert_Name IN (SELECT concert.concert_ID, I_concert.concert_Name FROM concert I_concert JOIN singer I_singer JOIN singer_in_concert I_singer_in_concert ON I_concert.concert_ID=I_singer_in_concert.concert_ID AND I_singer.Singer_ID=I_singer_in_concert.Singer_ID WHERE (O_concert.concert_ID = I_concert.concert_ID AND I_singer.Song_Name != "Sun") GROUP BY concert.concert_ID) ORDER BY concert.Theme
SELECT O_concert.Stadium_ID, O_singer_in_concert.concert_ID FROM concert O_concert JOIN singer O_singer JOIN singer_in_concert O_singer_in_concert ON O_concert.concert_ID=O_singer_in_concert.concert_ID AND O_singer.Singer_ID=O_singer_in_concert.Singer_ID WHERE ((SELECT I_concert.Theme FROM concert I_concert JOIN stadium I_stadium ON I_stadium.Stadium_ID=I_concert.Stadium_ID WHERE (O_stadium.Average = I_stadium.Average AND I_stadium.Capacity != 3808.0) ORDER BY concert.concert_Name LIMIT 2) != "Free choice" OR O_singer.Age != 32) ORDER BY singer.Is_male LIMIT 3
SELECT singer_in_concert.Singer_ID, SUM(O_stadium.Highest) FROM concert O_concert JOIN singer O_singer JOIN singer_in_concert O_singer_in_concert JOIN stadium O_stadium ON O_concert.concert_ID=O_singer_in_concert.concert_ID AND O_singer.Singer_ID=O_singer_in_concert.Singer_ID AND O_stadium.Stadium_ID=O_concert.Stadium_ID WHERE O_singer.Song_release_year NOT IN (SELECT singer.Is_male, I_singer.Song_release_year FROM concert I_concert JOIN singer I_singer JOIN singer_in_concert I_singer_in_concert JOIN stadium I_stadium ON I_concert.concert_ID=I_singer_in_concert.concert_ID AND I_singer.Singer_ID=I_singer_in_concert.Singer_ID AND I_stadium.Stadium_ID=I_concert.Stadium_ID WHERE (O_concert.Year = I_concert.Year AND (I_stadium.Stadium_ID != 10.0 OR I_stadium.Lowest != 466.0)) GROUP BY singer.Is_male) GROUP BY singer_in_concert.Singer_ID ORDER BY COUNT(stadium.Name)
SELECT O_singer.Song_Name, O_singer.Is_male FROM singer O_singer WHERE O_singer.Song_Name IN (SELECT I_singer.Song_Name FROM singer I_singer WHERE (O_singer.Name = I_singer.Name AND (I_singer.Is_male NOT LIKE "%F" OR (I_singer.Song_Name NOT IN "('Love','You','Dangerous','Gentleman','Sun')" OR I_singer.Song_Name != "Hey Oh"))))
SELECT singer_in_concert.concert_ID, COUNT(DISTINCT O_singer.Song_release_year), COUNT(DISTINCT O_singer.Name) FROM singer O_singer WHERE (O_singer.Age > 29 OR (O_singer.Song_release_year LIKE (SELECT I_singer.Song_release_year FROM singer I_singer WHERE (O_singer.Age = I_singer.Age AND I_singer.Singer_ID = 5) ORDER BY singer.Name) AND O_singer.Age <= 43)) GROUP BY singer_in_concert.concert_ID HAVING COUNT(singer.Name) > 3
SELECT singer_in_concert.concert_ID, COUNT(DISTINCT O_singer_in_concert.Singer_ID), MAX(O_singer_in_concert.concert_ID) FROM singer_in_concert O_singer_in_concert WHERE (SELECT concert.Theme, I_singer_in_concert.concert_ID FROM singer I_singer JOIN singer_in_concert I_singer_in_concert ON I_singer.Singer_ID=I_singer_in_concert.Singer_ID WHERE (O_singer_in_concert.Singer_ID = I_singer_in_concert.Singer_ID AND (I_singer_in_concert.concert_ID != 2.0 OR I_singer.Age != 52)) GROUP BY concert.Theme) <= 1.0 GROUP BY singer_in_concert.concert_ID HAVING singer_in_concert.concert_ID < 5.0
SELECT O_singer.Country FROM singer O_singer WHERE (O_singer.Country NOT IN "('Netherlands','United States')" AND (SELECT I_singer.Song_Name FROM singer I_singer WHERE (O_singer.Name = I_singer.Name AND I_singer.Song_Name != "Gentleman") ORDER BY singer.Song_release_year LIMIT 4) = "Love")
SELECT O_stadium.Name FROM stadium O_stadium WHERE O_stadium.Lowest >= (SELECT I_stadium.Lowest FROM concert I_concert JOIN singer_in_concert I_singer_in_concert JOIN stadium I_stadium ON I_concert.concert_ID=I_singer_in_concert.concert_ID AND I_stadium.Stadium_ID=I_concert.Stadium_ID WHERE (O_stadium.Location = I_stadium.Location AND (I_stadium.Highest < 1763.0 AND (I_singer_in_concert.concert_ID = 6.0 OR I_stadium.Lowest = 315.0))))
SELECT singer.Song_release_year, COUNT(DISTINCT O_concert.concert_ID) FROM concert O_concert JOIN singer O_singer JOIN singer_in_concert O_singer_in_concert JOIN stadium O_stadium ON O_concert.concert_ID=O_singer_in_concert.concert_ID AND O_singer.Singer_ID=O_singer_in_concert.Singer_ID AND O_stadium.Stadium_ID=O_concert.Stadium_ID WHERE (O_singer.Singer_ID != 1 AND (O_singer.Singer_ID IN (SELECT I_singer.Singer_ID FROM singer I_singer WHERE (O_singer.Country = I_singer.Country AND I_singer.Country NOT IN "('Netherlands','United States')")) AND O_stadium.Lowest != 400.0)) GROUP BY singer.Song_release_year ORDER BY singer.Song_Name
