SELECT O_singer.Age, O_singer.Is_male FROM singer O_singer WHERE O_singer.Song_Name != (SELECT stadium.Average, I_singer.Song_Name FROM singer I_singer GROUP BY stadium.Average HAVING (MAX(singer.Singer_ID) != 5 AND (COUNT(stadium.Location) = 2 AND COUNT(concert.Theme) > 3)) ORDER BY stadium.Stadium_ID LIMIT 1)
SELECT singer.Singer_ID, COUNT(DISTINCT O_singer_in_concert.Singer_ID) FROM concert O_concert JOIN singer_in_concert O_singer_in_concert JOIN stadium O_stadium ON O_concert.concert_ID=O_singer_in_concert.concert_ID AND O_stadium.Stadium_ID=O_concert.Stadium_ID WHERE (O_concert.concert_ID != 3.0 AND O_stadium.Lowest IN (SELECT stadium.Lowest, I_stadium.Lowest FROM stadium I_stadium GROUP BY stadium.Lowest HAVING (COUNT(stadium.Location) > 1 AND (SUM(stadium.Stadium_ID) = 5.0 OR COUNT(stadium.Location) >= 4)) ORDER BY stadium.Lowest LIMIT 1)) GROUP BY singer.Singer_ID HAVING (MIN(stadium.Capacity) < 11998.0 OR MAX(stadium.Average) != 1477.0)
SELECT COUNT(DISTINCT O_singer.Song_Name) FROM singer O_singer WHERE O_singer.Singer_ID NOT IN (SELECT singer.Is_male, I_singer.Singer_ID FROM singer I_singer WHERE (I_singer.Country = "Netherlands" OR I_singer.Name NOT LIKE "White%") GROUP BY singer.Is_male) ORDER BY singer.Is_male
SELECT singer_in_concert.Singer_ID, COUNT(DISTINCT O_singer_in_concert.Singer_ID) FROM singer_in_concert O_singer_in_concert WHERE O_singer_in_concert.concert_ID >= (SELECT stadium.Average, I_singer_in_concert.concert_ID FROM singer_in_concert I_singer_in_concert GROUP BY stadium.Average HAVING ((COUNT(stadium.Highest) >= 3 OR COUNT(stadium.Location) > 2) OR stadium.Average <= 552.0)) GROUP BY singer_in_concert.Singer_ID
SELECT stadium.Average, SUM(O_stadium.Lowest), MAX(O_stadium.Stadium_ID) FROM stadium O_stadium WHERE (O_stadium.Location != "Arbroath" AND O_stadium.Lowest <= (SELECT I_stadium.Lowest FROM concert I_concert JOIN stadium I_stadium ON I_stadium.Stadium_ID=I_concert.Stadium_ID WHERE (I_stadium.Location NOT IN "('Raith Rovers','Peterhead','Arbroath','Alloa Athletic')" OR I_concert.concert_Name != "Week 2") ORDER BY singer.Song_release_year LIMIT 4)) GROUP BY stadium.Average ORDER BY SUM(stadium.Highest) LIMIT 4
SELECT O_concert.concert_ID FROM concert O_concert JOIN stadium O_stadium ON O_stadium.Stadium_ID=O_concert.Stadium_ID WHERE (O_stadium.Lowest <= 466.0 AND O_stadium.Lowest IN (SELECT stadium.Lowest, I_stadium.Lowest FROM stadium I_stadium GROUP BY stadium.Lowest ORDER BY MAX(stadium.Stadium_ID))) ORDER BY stadium.Name
SELECT concert.concert_Name, COUNT(*) FROM concert O_concert WHERE O_concert.concert_Name != (SELECT concert.Stadium_ID, I_concert.concert_Name FROM concert I_concert GROUP BY concert.Stadium_ID) GROUP BY concert.concert_Name
SELECT stadium.Lowest, COUNT(DISTINCT O_stadium.Location), MAX(O_stadium.Stadium_ID) FROM stadium O_stadium WHERE O_stadium.Lowest NOT IN (SELECT I_stadium.Lowest FROM concert I_concert JOIN stadium I_stadium ON I_stadium.Stadium_ID=I_concert.Stadium_ID WHERE (I_concert.concert_Name != "Auditions" AND (I_stadium.Highest < 837.0 OR I_stadium.Name NOT IN "('Balmoor','Gayfield Park')")) ORDER BY concert.concert_Name) GROUP BY stadium.Lowest HAVING (MAX(stadium.Stadium_ID) = 10.0 OR COUNT(concert.Stadium_ID) != 3)
SELECT * FROM concert O_concert JOIN singer_in_concert O_singer_in_concert ON O_concert.concert_ID=O_singer_in_concert.concert_ID WHERE (O_singer_in_concert.concert_ID != 1.0 AND (O_concert.concert_ID != 5.0 AND O_concert.concert_ID IN (SELECT concert.Year, I_concert.concert_ID FROM concert I_concert WHERE I_concert.concert_ID != 1.0 GROUP BY concert.Year HAVING (COUNT(concert.Theme) = 3 OR (COUNT(concert.concert_Name) != 4 AND COUNT(concert.Stadium_ID) > 1)) ORDER BY concert.Theme LIMIT 1))) ORDER BY concert.concert_Name
SELECT stadium.Location, COUNT(*) FROM stadium O_stadium WHERE (O_stadium.Highest >= 2363.0 OR O_stadium.Highest >= (SELECT I_stadium.Highest FROM concert I_concert JOIN singer I_singer JOIN singer_in_concert I_singer_in_concert JOIN stadium I_stadium ON I_concert.concert_ID=I_singer_in_concert.concert_ID AND I_singer.Singer_ID=I_singer_in_concert.Singer_ID AND I_stadium.Stadium_ID=I_concert.Stadium_ID WHERE (I_stadium.Location NOT LIKE "%Arbroat" OR (I_singer.Country NOT IN "('United States','France')" AND I_stadium.Stadium_ID != 1.0)))) GROUP BY stadium.Location ORDER BY stadium.Capacity LIMIT 3
