SELECT O_stadium.Stadium_ID, O_stadium.Capacity FROM stadium O_stadium WHERE O_stadium.Highest != (SELECT singer.Country, SUM(I_stadium.Highest) FROM stadium I_stadium WHERE (O_stadium.Name = I_stadium.Name AND (I_stadium.Location NOT LIKE "%Arbroat%" AND I_stadium.Name != "Stark's Park")) GROUP BY singer.Country HAVING (MAX(stadium.Average) > 615.0 OR (COUNT(concert.concert_Name) > 1 OR COUNT(singer.Song_Name) > 3)) ORDER BY stadium.Name)
SELECT O_singer.Singer_ID FROM singer O_singer WHERE (O_singer.Song_Name != "Hey Oh" AND (SELECT COUNT(I_singer.Song_release_year) FROM concert I_concert JOIN singer I_singer JOIN singer_in_concert I_singer_in_concert ON I_concert.concert_ID=I_singer_in_concert.concert_ID AND I_singer.Singer_ID=I_singer_in_concert.Singer_ID WHERE (O_singer.Name = I_singer.Name AND I_concert.concert_Name != "Home Visits")) > 187) ORDER BY singer.Age
SELECT O_singer.Singer_ID, O_singer.Is_male FROM singer O_singer WHERE (O_singer.Country LIKE "Netherl%" AND (O_singer.Country != "United States" OR O_singer.Singer_ID >= (SELECT singer.Song_Name, MIN(I_singer.Singer_ID) FROM singer I_singer WHERE (O_singer.Song_Name = I_singer.Song_Name AND I_singer.Is_male != "'F'") GROUP BY singer.Song_Name ORDER BY singer.Age)))
SELECT COUNT(DISTINCT O_singer_in_concert.Singer_ID) FROM concert O_concert JOIN singer_in_concert O_singer_in_concert ON O_concert.concert_ID=O_singer_in_concert.concert_ID WHERE (O_concert.concert_Name LIKE "%Week%" AND O_concert.concert_ID >= (SELECT singer.Name, AVG(I_concert.concert_ID) FROM concert I_concert JOIN singer I_singer JOIN singer_in_concert I_singer_in_concert ON I_concert.concert_ID=I_singer_in_concert.concert_ID AND I_singer.Singer_ID=I_singer_in_concert.Singer_ID WHERE (O_singer_in_concert.concert_ID = I_singer_in_concert.concert_ID AND I_singer.Age <= 29) GROUP BY singer.Name ORDER BY COUNT(stadium.Highest) LIMIT 2)) ORDER BY concert.Year LIMIT 4
SELECT singer.Country, SUM(O_stadium.Stadium_ID) FROM concert O_concert JOIN singer O_singer JOIN singer_in_concert O_singer_in_concert JOIN stadium O_stadium ON O_concert.concert_ID=O_singer_in_concert.concert_ID AND O_singer.Singer_ID=O_singer_in_concert.Singer_ID AND O_stadium.Stadium_ID=O_concert.Stadium_ID WHERE (O_singer.Singer_ID = 1 OR (SELECT MIN(I_stadium.Capacity) FROM concert I_concert JOIN stadium I_stadium ON I_stadium.Stadium_ID=I_concert.Stadium_ID WHERE (O_concert.Theme = I_concert.Theme AND (I_stadium.Location = "Ayr United" AND I_concert.concert_Name IN "('Super bootcamp','Home Visits','Auditions')"))) > 11998.0) GROUP BY singer.Country ORDER BY singer.Singer_ID LIMIT 2
SELECT COUNT(DISTINCT O_singer.Song_release_year), COUNT(DISTINCT O_singer.Country) FROM singer O_singer WHERE ((O_singer.Country = "France" OR (SELECT concert.Stadium_ID, COUNT(I_singer.Song_release_year) FROM singer I_singer WHERE (O_singer.Age = I_singer.Age AND I_singer.Is_male NOT LIKE "F%") GROUP BY concert.Stadium_ID) != 152) OR O_singer.Song_Name LIKE "%You%")
SELECT singer_in_concert.Singer_ID, COUNT(*) FROM singer_in_concert O_singer_in_concert WHERE O_singer_in_concert.concert_ID != (SELECT singer_in_concert.Singer_ID, AVG(I_singer_in_concert.concert_ID) FROM singer_in_concert I_singer_in_concert WHERE (O_singer_in_concert.Singer_ID = I_singer_in_concert.Singer_ID AND I_singer_in_concert.concert_ID != 1.0) GROUP BY singer_in_concert.Singer_ID ORDER BY singer_in_concert.concert_ID LIMIT 4) GROUP BY singer_in_concert.Singer_ID HAVING (MIN(singer_in_concert.concert_ID) = 5.0 OR AVG(singer_in_concert.concert_ID) > 5.0) ORDER BY MAX(singer_in_concert.concert_ID)
SELECT stadium.Average, MIN(O_stadium.Stadium_ID), MIN(O_stadium.Capacity) FROM stadium O_stadium WHERE ((O_stadium.Lowest = 315.0 AND (SELECT concert.Stadium_ID, COUNT(I_stadium.Location) FROM stadium I_stadium WHERE (O_stadium.Capacity = I_stadium.Capacity AND I_stadium.Capacity <= 10104.0) GROUP BY concert.Stadium_ID) > 70) OR O_stadium.Lowest != 315.0) GROUP BY stadium.Average ORDER BY COUNT(stadium.Stadium_ID)
SELECT stadium.Stadium_ID, AVG(O_singer.Singer_ID) FROM singer O_singer WHERE (SELECT COUNT(I_singer_in_concert.concert_ID) FROM concert I_concert JOIN singer_in_concert I_singer_in_concert ON I_concert.concert_ID=I_singer_in_concert.concert_ID WHERE (O_stadium.Lowest = I_stadium.Lowest AND I_concert.Theme NOT IN "('Free choice 2','Party All Night','Bleeding Love')") ORDER BY concert.Year LIMIT 1) <= 181 GROUP BY stadium.Stadium_ID ORDER BY concert.concert_ID
SELECT singer_in_concert.Singer_ID, SUM(O_singer_in_concert.concert_ID) FROM singer_in_concert O_singer_in_concert WHERE (O_singer_in_concert.concert_ID != 2.0 OR O_singer_in_concert.concert_ID < (SELECT concert.Year, MAX(I_singer_in_concert.concert_ID) FROM concert I_concert JOIN singer_in_concert I_singer_in_concert JOIN stadium I_stadium ON I_concert.concert_ID=I_singer_in_concert.concert_ID AND I_stadium.Stadium_ID=I_concert.Stadium_ID WHERE (O_singer_in_concert.Singer_ID = I_singer_in_concert.Singer_ID AND I_stadium.Highest = 2363.0) GROUP BY concert.Year ORDER BY stadium.Lowest LIMIT 1)) GROUP BY singer_in_concert.Singer_ID
