SELECT * FROM Student O_Student WHERE (O_Student.city_code NOT IN "('HOU','CHI','WAS','BOS','NAR')" AND (O_Student.Sex IN (SELECT Student.LName, I_Student.Sex FROM Student I_Student GROUP BY Student.LName) OR O_Student.Age = 19)) ORDER BY Student.Sex
SELECT Student.Age, COUNT(DISTINCT O_Student.Sex) FROM Student O_Student WHERE (O_Student.LName IN (SELECT I_Student.LName FROM Student I_Student ORDER BY Student.Age) AND O_Student.Major = 520) GROUP BY Student.Age ORDER BY COUNT(Student.city_code)
SELECT Student.city_code, COUNT(*) FROM Student O_Student WHERE (O_Student.Age > 20 AND O_Student.city_code NOT IN (SELECT Student.Fname, I_Student.city_code FROM Student I_Student GROUP BY Student.Fname HAVING (SUM(Student.Major) < 600 AND COUNT(Student.Advisor) < 4))) GROUP BY Student.city_code
SELECT Student.Major, COUNT(DISTINCT O_Student.city_code) FROM Student O_Student WHERE (O_Student.Advisor != (SELECT Student.Fname, I_Student.Advisor FROM Student I_Student WHERE I_Student.LName NOT LIKE "%Thornto%" GROUP BY Student.Fname) OR O_Student.city_code = "ROC") GROUP BY Student.Major ORDER BY Student.Major LIMIT 4
SELECT O_Student.StuID, O_Student.Advisor FROM Student O_Student WHERE (O_Student.StuID = 1012 OR O_Student.Advisor IN (SELECT I_Student.Advisor FROM Student I_Student WHERE ((I_Student.LName IN "('Schwartz','Davis','Epp')" AND I_Student.Age = 17) OR I_Student.StuID = 1029))) ORDER BY Student.Age
SELECT COUNT(*) FROM Student O_Student WHERE (O_Student.Fname != (SELECT Student.city_code, I_Student.Fname FROM Student I_Student GROUP BY Student.city_code ORDER BY Student.LName LIMIT 4) AND (O_Student.city_code NOT IN "('NYC','NAR')" AND O_Student.LName NOT LIKE "%Lee")) ORDER BY Student.Major
SELECT * FROM Student O_Student WHERE O_Student.StuID NOT IN (SELECT Student.Age, I_Student.StuID FROM Student I_Student WHERE (I_Student.city_code = "NYC" OR (I_Student.LName NOT LIKE "%Schmidt" OR I_Student.LName = "Shieber")) GROUP BY Student.Age HAVING (Student.Age >= 22 AND (Student.Age = 22 AND COUNT(Student.Sex) <= 4)))
SELECT Student.Major, COUNT(DISTINCT O_Student.Fname), SUM(O_Student.StuID) FROM Student O_Student WHERE ((O_Student.Age >= 18 OR O_Student.Major NOT IN (SELECT I_Student.Major FROM Student I_Student ORDER BY Student.Major LIMIT 2)) OR O_Student.Major > 600) GROUP BY Student.Major
SELECT Student.Fname, COUNT(*) FROM Student O_Student WHERE O_Student.LName = (SELECT Student.city_code, I_Student.LName FROM Student I_Student GROUP BY Student.city_code ORDER BY COUNT(Student.Fname) LIMIT 2) GROUP BY Student.Fname HAVING (MIN(Student.Age) > 20 OR SUM(Student.Major) <= 550)
SELECT Student.Sex, SUM(O_Student.Major), SUM(O_Student.StuID) FROM Student O_Student WHERE (O_Student.Major = 600 AND O_Student.LName IN (SELECT Student.city_code, I_Student.LName FROM Student I_Student WHERE I_Student.Fname = "Susan" GROUP BY Student.city_code)) GROUP BY Student.Sex HAVING ((MIN(Student.Major) <= 600 AND MAX(Student.Advisor) >= 7723) AND Student.Sex NOT IN "("('F')", 1)") ORDER BY AVG(Student.Age) LIMIT 3
