SELECT Student.Fname, COUNT(DISTINCT O_Student.Sex), COUNT(DISTINCT O_Student.Fname) FROM Student O_Student WHERE ((O_Student.Major >= 50 AND O_Student.LName LIKE "Schmidt%") OR O_Student.Advisor >= (SELECT Student.StuID, SUM(I_Student.Advisor) FROM Student I_Student GROUP BY Student.StuID HAVING (AVG(Student.Age) > 17 OR (COUNT(Student.city_code) = 2 OR COUNT(Student.Sex) != 1)))) GROUP BY Student.Fname HAVING COUNT(Student.StuID) <= 3 ORDER BY Student.Sex LIMIT 4
SELECT COUNT(DISTINCT O_Student.Advisor) FROM Student O_Student WHERE (O_Student.Fname = "Linda" OR O_Student.Age = (SELECT MAX(I_Student.Age) FROM Student I_Student ORDER BY Student.city_code)) ORDER BY Student.Fname
SELECT Student.Major, COUNT(*) FROM Student O_Student WHERE (O_Student.StuID != 1006 OR O_Student.StuID <= (SELECT Student.LName, AVG(I_Student.StuID) FROM Student I_Student WHERE (I_Student.city_code NOT LIKE "%PIT%" AND I_Student.LName LIKE "%Tai") GROUP BY Student.LName ORDER BY Student.city_code LIMIT 3)) GROUP BY Student.Major HAVING COUNT(Student.city_code) != 1 ORDER BY Student.LName
SELECT O_Student.StuID FROM Student O_Student WHERE (O_Student.Major < 550 OR (O_Student.Advisor > 8721 AND O_Student.StuID <= (SELECT Student.city_code, SUM(I_Student.StuID) FROM Student I_Student WHERE ((I_Student.StuID = 1032 OR I_Student.Advisor >= 7271) AND I_Student.city_code = "ATL") GROUP BY Student.city_code HAVING (MIN(Student.Age) >= 17 AND (COUNT(Student.Fname) <= 1 AND COUNT(Student.Sex) < 2))))) ORDER BY Student.city_code LIMIT 2
SELECT Student.Sex, COUNT(DISTINCT O_Student.Fname), COUNT(DISTINCT O_Student.city_code) FROM Student O_Student WHERE O_Student.Major != (SELECT SUM(I_Student.Major) FROM Student I_Student WHERE I_Student.Fname = "Ian") GROUP BY Student.Sex ORDER BY Student.LName
SELECT O_Student.Age, O_Student.Major FROM Student O_Student WHERE O_Student.Major < (SELECT Student.city_code, AVG(I_Student.Major) FROM Student I_Student WHERE I_Student.Age != 20 GROUP BY Student.city_code)
SELECT * FROM Student O_Student WHERE O_Student.StuID < (SELECT Student.Advisor, SUM(I_Student.StuID) FROM Student I_Student WHERE I_Student.LName NOT LIKE "%Kumar" GROUP BY Student.Advisor HAVING COUNT(Student.LName) < 4)
SELECT O_Student.Fname, O_Student.Sex FROM Student O_Student WHERE O_Student.Age < (SELECT Student.Advisor, MAX(I_Student.Age) FROM Student I_Student WHERE (I_Student.Sex != "'F'" AND I_Student.LName NOT LIKE "Andreou%") GROUP BY Student.Advisor)
SELECT O_Student.LName FROM Student O_Student WHERE (O_Student.Advisor > (SELECT Student.city_code, AVG(I_Student.Advisor) FROM Student I_Student GROUP BY Student.city_code HAVING Student.city_code = "WAS" ORDER BY COUNT(Student.Fname)) AND (O_Student.Advisor >= 1148 AND O_Student.Sex != "'F'"))
SELECT * FROM Student O_Student WHERE O_Student.StuID <= (SELECT Student.Fname, AVG(I_Student.StuID) FROM Student I_Student GROUP BY Student.Fname HAVING ((SUM(Student.StuID) >= 1033 OR AVG(Student.Age) = 18) OR AVG(Student.Advisor) >= 8772) ORDER BY SUM(Student.StuID) LIMIT 4)
