SELECT Student.city_code, COUNT(DISTINCT Student.Sex), MAX(Student.StuID) FROM Student WHERE (Student.Advisor > 2311 OR Student.Sex IN "('M','F')") GROUP BY Student.city_code HAVING (Student.city_code LIKE "PHL%" AND SUM(Student.Advisor) = 8722) ORDER BY Student.Advisor
SELECT Student.StuID, COUNT(*) FROM Student WHERE Student.Fname NOT LIKE "%Linda" GROUP BY Student.StuID HAVING COUNT(Student.Fname) > 3 ORDER BY COUNT(Student.Sex)
SELECT Student.city_code, COUNT(*) FROM Student WHERE (Student.Major < 600 OR Student.Sex != "'M'") GROUP BY Student.city_code HAVING COUNT(Student.Fname) > 4 ORDER BY Student.LName
SELECT Student.StuID, COUNT(DISTINCT Student.Advisor) FROM Student WHERE (Student.Sex IN "('M','F')" OR Student.Advisor >= 7792) GROUP BY Student.StuID HAVING COUNT(Student.LName) <= 2 ORDER BY COUNT(Student.Fname)
SELECT Student.city_code, COUNT(DISTINCT Student.Sex) FROM Student WHERE (Student.Fname != "Arthur" AND Student.Major = 520) GROUP BY Student.city_code HAVING COUNT(Student.Age) <= 3 ORDER BY Student.StuID
SELECT Student.city_code, COUNT(*) FROM Student WHERE Student.Fname LIKE "%George%" GROUP BY Student.city_code HAVING (Student.city_code NOT LIKE "%DET" OR (MAX(Student.Major) <= 600 AND COUNT(Student.Sex) <= 2)) ORDER BY Student.StuID
SELECT Student.Sex, COUNT(DISTINCT Student.Sex) FROM Student WHERE Student.Sex != "F" GROUP BY Student.Sex HAVING MIN(Student.StuID) < 1029 ORDER BY SUM(Student.Major)
SELECT Student.Age, AVG(Student.Major), COUNT(DISTINCT Student.city_code) FROM Student WHERE (Student.Fname != "Jun" OR (Student.Age >= 19 AND Student.Age > 19)) GROUP BY Student.Age HAVING COUNT(Student.Fname) > 2 ORDER BY COUNT(Student.city_code)
SELECT Student.Fname, COUNT(*) FROM Student WHERE ((Student.StuID != 1030 OR Student.Fname NOT LIKE "%Sarah%") OR Student.LName IN "('Apap','Goldman','Adams','Norris')") GROUP BY Student.Fname HAVING AVG(Student.StuID) < 1031 ORDER BY Student.city_code
SELECT Student.LName, COUNT(DISTINCT Student.LName), MIN(Student.StuID) FROM Student WHERE ((Student.Advisor < 2311 OR Student.city_code LIKE "YYZ%") AND Student.Advisor > 1148) GROUP BY Student.LName HAVING (COUNT(Student.Sex) >= 4 AND COUNT(Student.Fname) = 4) ORDER BY Student.StuID
SELECT Student.StuID, COUNT(*) FROM Student WHERE (Student.LName NOT IN "('Tai','Gompers','Han')" OR Student.LName != "Rugh") GROUP BY Student.StuID HAVING COUNT(Student.Sex) >= 3 ORDER BY Student.StuID
SELECT Student.city_code, MAX(Student.Advisor), COUNT(DISTINCT Student.Sex) FROM Student WHERE ((Student.LName LIKE "%Goldman%" AND Student.Fname LIKE "%Mark") OR Student.LName LIKE "%Goldman%") GROUP BY Student.city_code HAVING (MAX(Student.Advisor) >= 7271 AND SUM(Student.Advisor) < 7271) ORDER BY Student.Advisor
SELECT Student.Age, COUNT(*) FROM Student WHERE (Student.Advisor = 9172 AND Student.Advisor > 2192) GROUP BY Student.Age HAVING (COUNT(Student.LName) = 1 AND (SUM(Student.Advisor) >= 7134 OR COUNT(Student.Major) != 2)) ORDER BY COUNT(Student.city_code)
SELECT Student.StuID, SUM(Student.Advisor), COUNT(DISTINCT Student.city_code) FROM Student WHERE Student.Major < 600 GROUP BY Student.StuID HAVING (Student.StuID <= 1012 OR AVG(Student.Major) > 600) ORDER BY SUM(Student.Major)
SELECT Student.Advisor, COUNT(DISTINCT Student.Fname) FROM Student WHERE Student.LName NOT LIKE "%Kumar" GROUP BY Student.Advisor HAVING COUNT(Student.LName) < 4 ORDER BY Student.StuID
SELECT Student.Fname, SUM(Student.Advisor) FROM Student WHERE Student.Advisor >= 8423 GROUP BY Student.Fname HAVING (COUNT(Student.city_code) = 4 AND COUNT(Student.city_code) <= 4) ORDER BY COUNT(Student.LName)
SELECT Student.StuID, COUNT(*) FROM Student WHERE (Student.city_code LIKE "DAL%" OR Student.Age >= 18) GROUP BY Student.StuID HAVING (COUNT(Student.Fname) < 4 OR (COUNT(Student.Fname) < 4 OR COUNT(Student.Sex) < 4)) ORDER BY Student.Major
SELECT Student.Advisor, COUNT(*) FROM Student WHERE Student.Advisor != 1148 GROUP BY Student.Advisor HAVING (COUNT(Student.city_code) < 4 OR (COUNT(Student.city_code) < 4 AND SUM(Student.StuID) != 1028)) ORDER BY Student.LName
SELECT Student.StuID, COUNT(*) FROM Student WHERE Student.Sex != "M" GROUP BY Student.StuID HAVING MIN(Student.Major) >= 550 ORDER BY Student.Advisor
SELECT Student.Sex, COUNT(DISTINCT Student.LName) FROM Student WHERE (Student.Age <= 20 AND (Student.Age != 21 OR Student.Age <= 17)) GROUP BY Student.Sex HAVING (Student.Sex NOT IN "("('F')", 1)" OR (COUNT(Student.Fname) != 3 AND MIN(Student.Major) > 600)) ORDER BY Student.Advisor
