SELECT * FROM Student O_Student WHERE (O_Student.city_code NOT IN "('HOU','CHI','WAS','BOS','NAR')" AND ((SELECT COUNT(I_Student.Fname) FROM Student I_Student WHERE (O_Student.Sex = I_Student.Sex AND I_Student.Major = 550) ORDER BY Student.LName LIMIT 4) > 65 OR O_Student.Age = 19)) ORDER BY Student.Fname
SELECT * FROM Student O_Student WHERE (O_Student.StuID != 1024 AND O_Student.Advisor >= (SELECT Student.StuID, AVG(I_Student.Advisor) FROM Student I_Student WHERE (O_Student.Age = I_Student.Age AND (I_Student.Sex = "M" AND I_Student.LName = "Simms")) GROUP BY Student.StuID ORDER BY Student.Sex))
SELECT O_Student.Age FROM Student O_Student WHERE (O_Student.city_code != "HOU" AND O_Student.Major >= (SELECT MIN(I_Student.Major) FROM Student I_Student WHERE (O_Student.Age = I_Student.Age AND (I_Student.StuID != 1030 OR (I_Student.Advisor = 9172 OR I_Student.Fname NOT LIKE "%Sarah"))) ORDER BY Student.Advisor LIMIT 2))
SELECT O_Student.Major, O_Student.Fname FROM Student O_Student WHERE O_Student.StuID >= (SELECT AVG(I_Student.StuID) FROM Student I_Student WHERE (O_Student.Fname = I_Student.Fname AND (I_Student.city_code IN "('PHL','HKG','HOU','BAL')" OR I_Student.Major >= 520))) ORDER BY Student.Fname
SELECT Student.city_code, COUNT(*) FROM Student O_Student WHERE (O_Student.Major > (SELECT MIN(I_Student.Major) FROM Student I_Student WHERE (O_Student.LName = I_Student.LName AND I_Student.Major <= 600) ORDER BY Student.Age LIMIT 3) OR (O_Student.StuID = 1010 AND O_Student.LName != "Gompers")) GROUP BY Student.city_code HAVING ((SUM(Student.StuID) >= 1009 OR Student.city_code NOT IN "("('ATL','HOU','LON','WAS')", 4)") AND COUNT(Student.Fname) >= 2)
SELECT O_Student.Major FROM Student O_Student WHERE (O_Student.Age < 18 AND ((SELECT COUNT(I_Student.Fname) FROM Student I_Student WHERE (O_Student.Age = I_Student.Age AND I_Student.StuID != 1020) ORDER BY Student.Sex) <= 116 AND O_Student.Age = 17))
SELECT O_Student.StuID, O_Student.LName FROM Student O_Student WHERE (O_Student.Major <= 600 OR O_Student.Major < (SELECT SUM(I_Student.Major) FROM Student I_Student WHERE (O_Student.Fname = I_Student.Fname AND (I_Student.Fname NOT LIKE "%Michael" AND (I_Student.city_code NOT LIKE "%SFO" AND I_Student.LName != "Smith"))) ORDER BY Student.city_code LIMIT 3)) ORDER BY Student.LName
SELECT Student.Major, COUNT(*) FROM Student O_Student WHERE ((SELECT Student.city_code, SUM(I_Student.Major) FROM Student I_Student WHERE (O_Student.Sex = I_Student.Sex AND (I_Student.Age != 18 OR I_Student.LName = "Jones")) GROUP BY Student.city_code HAVING ((SUM(Student.Advisor) > 7723 OR COUNT(Student.Sex) < 4) OR COUNT(Student.Fname) >= 3) ORDER BY Student.Major LIMIT 1) = 264680 AND O_Student.city_code != "BOS") GROUP BY Student.Major HAVING AVG(Student.StuID) >= 1034
SELECT Student.Fname, COUNT(*) FROM Student O_Student WHERE O_Student.Major > (SELECT MIN(I_Student.Major) FROM Student I_Student WHERE (O_Student.city_code = I_Student.city_code AND (I_Student.city_code = "WAS" OR (I_Student.Fname != "Mark" AND I_Student.Major = 600)))) GROUP BY Student.Fname
SELECT COUNT(*) FROM Student O_Student WHERE (O_Student.Major < 520 OR (SELECT COUNT(I_Student.Sex) FROM Student I_Student WHERE (O_Student.Age = I_Student.Age AND ((I_Student.Fname != "David" OR I_Student.Major <= 600) OR I_Student.Major != 550))) >= 116) ORDER BY Student.Advisor LIMIT 4
