SELECT * FROM Student O_Student WHERE (O_Student.city_code NOT IN "('HOU','CHI','WAS','BOS','NAR')" AND ((SELECT Student.StuID, I_Student.Fname FROM Student I_Student WHERE (O_Student.Sex = I_Student.Sex AND (I_Student.Sex IN "('M','F')" OR I_Student.Advisor >= 7792)) GROUP BY Student.StuID HAVING COUNT(Student.LName) <= 2) != "Andy" OR O_Student.Age = 19)) ORDER BY Student.Sex
SELECT Student.Age, COUNT(DISTINCT O_Student.Sex) FROM Student O_Student WHERE (SELECT I_Student.Age FROM Student I_Student WHERE (O_Student.Fname = I_Student.Fname AND I_Student.Fname IN "('Tracy','Derek','Susan')") ORDER BY Student.city_code LIMIT 4) != 17 GROUP BY Student.Age ORDER BY MIN(Student.StuID) LIMIT 3
SELECT * FROM Student O_Student WHERE (O_Student.Fname NOT IN (SELECT Student.Sex, I_Student.Fname FROM Student I_Student WHERE (O_Student.Sex = I_Student.Sex AND ((I_Student.city_code NOT IN "('PHL','CHI','NYC')" AND I_Student.Fname NOT LIKE "%Linda%") AND I_Student.Major >= 550)) GROUP BY Student.Sex HAVING (Student.Sex LIKE "%F" OR COUNT(Student.city_code) < 1)) OR O_Student.Fname NOT LIKE "%Lisa")
SELECT Student.city_code, COUNT(*) FROM Student O_Student WHERE (O_Student.Advisor > 1148 AND (SELECT I_Student.city_code FROM Student I_Student WHERE (O_Student.Age = I_Student.Age AND ((I_Student.Advisor < 5718 AND I_Student.LName NOT IN "('Goldman','Han','Schultz','Nelson')") OR I_Student.city_code = "ROC"))) = "DET") GROUP BY Student.city_code
SELECT Student.StuID, COUNT(DISTINCT O_Student.Sex), COUNT(DISTINCT O_Student.Fname) FROM Student O_Student WHERE (O_Student.LName LIKE "%Gompers" OR O_Student.Major NOT IN (SELECT I_Student.Major FROM Student I_Student WHERE (O_Student.city_code = I_Student.city_code AND (I_Student.StuID = 1031 OR I_Student.Advisor != 8772)))) GROUP BY Student.StuID HAVING (COUNT(Student.Major) != 3 AND COUNT(Student.LName) > 2) ORDER BY Student.StuID
SELECT * FROM Student O_Student WHERE (O_Student.LName != "Smith" OR O_Student.Age IN (SELECT I_Student.Age FROM Student I_Student WHERE (O_Student.Advisor = I_Student.Advisor AND I_Student.city_code = "NAR") ORDER BY Student.Age LIMIT 1))
SELECT O_Student.Age, O_Student.Major FROM Student O_Student WHERE O_Student.Sex NOT IN (SELECT Student.LName, I_Student.Sex FROM Student I_Student WHERE (O_Student.Major = I_Student.Major AND I_Student.Fname = "Jandy") GROUP BY Student.LName)
SELECT Student.Sex, COUNT(DISTINCT O_Student.city_code), COUNT(DISTINCT O_Student.LName) FROM Student O_Student WHERE ((O_Student.Major != 550 OR O_Student.Advisor <= 7792) OR O_Student.Major NOT IN (SELECT Student.Fname, I_Student.Major FROM Student I_Student WHERE (O_Student.LName = I_Student.LName AND I_Student.Age != 26) GROUP BY Student.Fname)) GROUP BY Student.Sex ORDER BY MAX(Student.StuID) LIMIT 4
SELECT Student.Age, COUNT(*) FROM Student O_Student WHERE ((O_Student.city_code != "'CHI'" OR O_Student.Sex IN (SELECT Student.city_code, I_Student.Sex FROM Student I_Student WHERE (O_Student.Advisor = I_Student.Advisor AND (I_Student.Fname = "Lisa" OR I_Student.Major < 600)) GROUP BY Student.city_code ORDER BY MIN(Student.Advisor) LIMIT 2)) AND O_Student.Advisor > 2311) GROUP BY Student.Age ORDER BY Student.StuID
SELECT * FROM Student O_Student WHERE O_Student.Age != (SELECT I_Student.Age FROM Student I_Student WHERE (O_Student.Major = I_Student.Major AND (I_Student.LName = "Cheng" AND I_Student.LName LIKE "%Cheng"))) ORDER BY Student.city_code LIMIT 3
