export const operatorDescriptions = {
    "<": "< is an operator used to compare two values and return a Boolean value of true or false depending on whether the left operand is less than the right operand. The operator can be used with a variety of data types, including integers, floating-point numbers, and strings.",
    ">": "> is an operator used to compare two values and return a Boolean value of true or false depending on whether the left operand is greater than the right operand. The operator can be used with a variety of data types, including integers, floating-point numbers, and strings.",
    "=": "= is an operator used to compare two values and return a Boolean value of true or false depending on whether the values are equal. The operator can be used with a variety of data types, including integers, floating-point numbers, and strings.",
    "!=": "!= is an operator used to compare two values and return a Boolean value of true or false depending on whether the values are not equal. The operator can be used with a variety of data types, including integers, floating-point numbers, and strings.",
    "<=": "<= is an operator used to compare two values and return a Boolean value of true or false depending on whether the left operand is less than or equal to the right operand. The operator can be used with a variety of data types, including integers, floating-point numbers, and strings.",
    ">=": ">= is an operator used to compare two values and return a Boolean value of true or false depending on whether the left operand is greater than or equal to the right operand. The operator can be used with a variety of data types, including integers, floating-point numbers, and strings.",
    count: "Count is an aggregation function that is used to calculate the total number of rows or records in a table.",
    sum: "Sum is an aggregation function that is used to calculate the total sum of values in a given column of a table.",
    avg: "Avg is an aggregation function that is used to calculate the average value of a given column of a table.",
    min: "Min is an aggregation function that is used to calculate the minimum value of a given column of a table.",
    max: "Max is an aggregation function that is used to calculate the maximum value of a given column of a table.",
    Group: "Group is a function that is used to group data based on one or more columns in a table.",
    Order: "Order is a function that is used to sort data in a table based on the values in one or more columns. The function allows for the sorting of data in ascending or descending order based on the values in one or more columns.",
    EXISTS: "EXISTS is a boolean function that is used to test for the existence of a value in a column.",
    "NOT EXISTS": "Not EXISTS is a boolean function that is used to test for the non-existence of a row in a subquery.",
    IN: "IN is an boolean operator used to test whether a value is in a list of values.",
    "NOT IN": "NOT IN is an boolean operator used to test whether a value is not in a list of values.",
};
